### ISSUE TITLE
Instant Edit

### ISSUE THREAD

**Issue by rdepena** [openfin/fin-hypergrid#10]
Excel like instant edit feature where the editing starts as soon as you begin typing.

**Comment by osbert-messerfs** [comment]
+1

**Comment by joebo** [comment]
You can add an key-down event listener to trigger cell editor activation:

Example:

            grid.addFinEventListener('fin-keydown', function(event) {
                if (event.detail.char == "RETURN") {
                    var cell = grid.getSelectionModel().getSelections()[0].origin;
                    grid.editAt(grid.getCellEditorAt(cell.x,cell.y), { gridCell: cell });
                }
            });

**Comment by Dwaynekj** [comment]
No longer a priority
