### ISSUE TITLE
Column/row selection

### ISSUE THREAD

**Issue by rdepena** [openfin/fin-hypergrid#11]
clicking on the column header or column, you can select the entire row/column, in excel fashion.

**Comment by snackycracky** [comment]
The bclys example leverages some events which are not documented:
- fin-column-selection-changed
- fin-row-selection-changed

are those events going to be in production ?

Also this event uses the methods `getSelectedRows()` and `getSelectedColumns()`:
```
        jsonGrid.addFinEventListener('fin-selection-changed', function(e){
            console.log(jsonGrid.getSelectedRows(), jsonGrid.getSelectedColumns(), jsonGrid.getSelections());
        });

```
will this in Production as well ?

At the Moment I detect the selections like this:

```

            //copied from https://github.com/openfin/fin-hypergrid/blob/master/fin-hypergrid.dev.html#L17565
            // implementation details of the method: createExcelDataFromSelections
            let selectedRows = [];
            jsonGrid.addFinEventListener('fin-selection-changed', function (event) {
                let selections = jsonGrid.getSelectionModel().getSelections();
                selectedRows = selections.map(selection => tableJson[selection.origin.y].id);
            });

```

**Comment by stevewirts** [comment]
this branch will eventually become the production version, we're shooting for eoy
