### ISSUE TITLE
expanded documentation

### ISSUE THREAD

**Issue by rafikam** [openfin/fin-hypergrid#12]
Hi. I'm very excited by the demo of your product and looking to start working with hypergrid. I have a few questions regarding the use of it. I'm not sure this is the best place for these questions, so if there's a better venue- please suggest.

Would love to see more explicit documentation on adding hypergrid to an existing app. I have an angular app I want to add hypergrid to it.

I tried following this remark from your repo page:

> The only js file that is necessary to deploy the hypergrid is fin-hypergrid.min.js which is a vulcanzed conglomeration of all code and dependencies required by fin-hypergrid. An example of this is found here. 

But the linked example page doesn't actually use fin-hypergrid.min.js at all. Please clarify.

Also, I'm interested in instructions regarding integration of your Polymer component with Angular and documentation on how to generally set and manipulate the grid's data. Can I use an array of objects in controller scope as my hypergrid data source?

Your API has a setValue function for a given cell but I need to add or delete rows from the already displayed data based on an outside event. Is that functionality possible? If I update the JS data in that fashion (adding/deleting/updating rows) will the UI automatically follow suit or what steps need to be taken?

Look forward to learning more on this very promising component. Thanks.

**Comment by chuckdoerr** [comment]
One of the engineers that works on hypergrid will get back shortly but in case this is helpful have a look at the hypergrid used in a small angular app here - https://github.com/datamadic/hypergrid-map

**Comment by rafikam** [comment]
@chuckdoerr Thanks for the quick reply. I'll certainly give it a look.

**Comment by stevewirts** [comment]
Hi,
more and better documentation is on our short term todo list...

you can edit the array of objects in the json behavior any way you want,
add, remove, delete items, then call
sizeChanged() on the behavior which will cause a repaint in the grid,
everything should work smoothly.

in a webcomponent compliant browser all you need to do to use the hypergrid
is to import fin-hypergrid.min.html in the head section of your page, heres
the source for the online standalone example....

view-source:http://openfin.github.io/example-fin-hypergrid-behavior-json/

please keep using hypergrid and spread the word, let us know what you think
and if you find issues bugs, etc....
thanks!

-steve

**Comment by rafikam** [comment]
Thanks for setting me in the right direction. Playing with the JSON example has been a big help.

I'll post again when I hit further issues. Cheers.
