### ISSUE TITLE
demo links not working

### ISSUE THREAD

**Issue by realsaraf** [openfin/fin-hypergrid#122]
hi guys,

have been waiting for the release for a long time. However the demo link is not working. Any clue?

**Comment by Dwaynekj** [comment]
@realsaraf Hey thanks for the heads up. We ran into a little hiccup with our build script. We've been aware of the issue and will resolve today

**Comment by Dwaynekj** [comment]
hey @realsaraf quick update. All the links, besides the old polymer demo should work. We are still in the midst of fixing that and should have it resolved soon. We also plan to provide new examples (similar to or exact replicas of the polymer examples) for 1.0

**Comment by realsaraf** [comment]
@Dwaynekj Thats awesome. Thanks for the quick turnaround.

**Comment by Dwaynekj** [comment]
All demo links are fixed
