### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by ahmednuaman** [openfin/fin-hypergrid#13]
We're looking to use hypergrid but the last release was in November; is there any news on when the latest one will come about?

**Comment by stevewirts** [comment]
Hi Ahmed,

We have been continually fixing issues, adding features, documenting, etc...
 all of the latest stuff is in master in github, if you update your project you should have the latest.
Currently we're looking at putting in paging/filtering/column selection.  If you have issues or requirements please pass them along and we can prioritze and include them in our roadmap.

-steve

**Comment by ahmednuaman** [comment]
Ok cool, will try master now.
