### ISSUE TITLE
More specific CSS?

### ISSUE THREAD

**Issue by ahmednuaman** [openfin/fin-hypergrid#16]
It'll be handy to see what CSS is actually required by hypergrid. The problem with importing one of the themes is that it overrides a lot of our CSS.

**Comment by stevewirts** [comment]
the hypergrid supports themes but they aren't required, there's a
precedence mechanism for setting the visual properties you can hook into at
any level, it uses a prototype chain,

see line 150 of
https://github.com/openfin/fin-hypergrid/blob/master/fin-hypergrid-renderer.html

**Comment by ahmednuaman** [comment]
Ok cool, it's interesting when I don't use a theme in its entirety I get rendering problems. I'm just trying to work through it but any pointers would be handy:

**Good**
![good](https://cloud.githubusercontent.com/assets/99223/6247965/92a60be2-b772-11e4-88ee-7c4c47ab2e26.gif)

**Bad**
![bad](https://cloud.githubusercontent.com/assets/99223/6247967/970dafb4-b772-11e4-9d90-396d3e36ecef.gif)

**Comment by stevewirts** [comment]
Hi Ahmed,

I've added a test in the renderer to not load the theme if there isn't a
theme used :)
so that cleared up this issue for me, let me know if that fixes things for
you

-steve

**Comment by ahmednuaman** [comment]
:beers:
