### ISSUE TITLE
Proper versioning for dependencies?

### ISSUE THREAD

**Issue by ahmednuaman** [openfin/fin-hypergrid#17]
So at the moment there's a problem with Polymer/core-collapse (https://github.com/Polymer/core-collapse/pull/19) that's causing an issue with installing `fin-hypergrid#master` branch. Is it possible to lock down the versions of the dependencies so we can have rainbows and unicorns again please?

**Comment by stevewirts** [comment]
Thanks for the heads up,
they've been locked to version 5.4.0
