### ISSUE TITLE
Rerendering

### ISSUE THREAD

**Issue by ahmednuaman** [openfin/fin-hypergrid#18]
So unless I'm being _really_ dumb (which there certainly is a possibility of this) I'm having issues re-rendering the table. I've created a little example: http://ahmednuaman.github.io/hypergrid-rerender-test/

From your demos it appears that you're just hiding and showing each "tab", whereas with most modern JS frameworks they add and remove HTML partials from the main views. The demo I've created essentially does that. Loads a HTML partial containing the table, gives it data, then if you hit the load button again it all starts off cool but no data is displayed.

I've spent some time looking into this and I can see the methods hitting the table, the table flushing the buffer canvas cache and so on, but nothing is rendered. What's also interesting is that for each time the table is re-rendered it adds two new buffer `<canvas>` elements, I'm thinking that these can probably be given an `id` so they can be reused somehow, maybe by providing it with a name?

**Comment by stevewirts** [comment]
I'll take a look,

**Comment by ahmednuaman** [comment]
Thanks. I'm doing some checking myself too.

**Comment by stevewirts** [comment]
Hi Ahmed,
I got it to work doing 2 things,
1) you don't want to import the fin-hypergrid.html file more than once, so
that import needs to be placed globally in your main document;
2) there are polymer lifecycle callback issues that haven't been resolved
yet, I've incorporated a reasonable yet imperfect solution for now,

I added a artificial load event for the fin-hypergrid and you can hook into
that. It gets called AFTER the hypergrid is ready.  All you need to do is
use this,

see...
http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/examples/partialtest.html

**Comment by ahmednuaman** [comment]
Amazing!
