### ISSUE TITLE
remove selectAll() on edit focus?

### ISSUE THREAD

**Issue by RaghavPro** [openfin/fin-hypergrid#181]
When you try to edit something, the focus event gets fired which calls a custom `selectAll` function.

with 'type to edit' as you go on typing it ends up overwriting the first character because it was selected. 
so for example, if you enter `fin-hypergrid` in a cell it becomes `in-hypergrid`

**Comment by Dwaynekj** [comment]
@RaghavPro Thanks for the PR. We will evaluate it as apart of current sprint

**Comment by RaghavPro** [comment]
Hi. I'm planning to use this and would love to contribute.

Let me know if the PR need any changes.



On Fri, Jun 24, 2016 at 9:33 PM +0530, "Dwayne Jones" <notifications@github.com<mailto:notifications@github.com>> wrote:


@RaghavPro<https://github.com/RaghavPro> Thanks for the PR. We will evaluate it as apart of current sprint

-

**Comment by Dwaynekj** [comment]
Will do. We will be reviewing the code this week

**Comment by Dwaynekj** [comment]
Hey @RaghavPro Would you mind creating a quick 1min demo movie demonstrating issue (using standard video formats that quicktime or a VLC player could run)? Alternatively we can do a quick 5 min screenshare. We are EST

**Comment by RaghavPro** [comment]
Screen share sounds good. I'm free right now if you are.

**Comment by Dwaynekj** [comment]
Send a skype invite to dj_openfin

**Comment by Dwaynekj** [comment]
Update: No party can reproduce. Closing issue
