### ISSUE TITLE
A way to define formula function at column level

### ISSUE THREAD

**Issue by RaghavPro** [openfin/fin-hypergrid#186]
Right now you have to set it for each cell of that column. It would be great if you can set it via column properties.

Thoughts?

**Comment by Dwaynekj** [comment]
Hey @RaghavPro We'll have an internal discussion this week.

**Comment by Dwaynekj** [comment]
What "formula" are you  referring to? Are you trying to do a calculated columns?

**Comment by RaghavPro** [comment]
Yes, calculated column. There should be a way to define it at column level.

**Comment by Dwaynekj** [comment]
@RaghavPro At the moment you we don't have this feature. I will add it to the list of desired features on the community wiki
