### ISSUE TITLE
Table Height and Width

### ISSUE THREAD

**Issue by juliuszc** [openfin/fin-hypergrid#188]
Hi,

Is there a way to specify the table height and table width? I see there is rowHeight, and fixedRowCount, so I could calculate it myself. Also I was also wondering if there could be a gitter channel created or something that would allow people to ask questions instead of having to open issues for help.

Thanks,
Juliusz

**Comment by Dwaynekj** [comment]
@juliuszc You can try controlling the height of the grid by adjusting the css of the containing element.

Re a community channel, at the moment we have a bit of internal work to conclude and its much easier for us to track and prioritize items with github issues and our JIRA (which we use internally). We have a community slack in mind for the future

**Comment by juliuszc** [comment]
@Dwaynekj Sorry to bother you again Dwayne, but I tried to adjust the css of the containing element and the hypergrid is inheriting from the wrong element. It's inheriting the height from a div way up the tree and painting over some other divs. Is there a specific way to pass to do this? I'm using react and this is the render method. 
 ```
render () {
    return (
      <div style={{border: "solid", borderColor: "purple", height: "200px", maxHeight: "200px"}}>
        <div id={`${this.props.id}`}></div>
      </div>
    )
  }
```

**Comment by Dwaynekj** [comment]
Hey @juliuszc This would be easier to debug with a demo. Can you host a demo somewhere that I can look at? Even its just the minimal amount of code.

**Comment by juliuszc** [comment]
You can see here that the canvas doesn't respect the immediate max height or width.
http://codepen.io/anon/pen/akWRdL

**Comment by Dwaynekj** [comment]
Hey @juliuszc I will followup with you for next week.

**Comment by juliuszc** [comment]
Hi @Dwaynekj. Just wondering if you've had any time to take a peek at the demo.

**Comment by Dwaynekj** [comment]
@juliuszc I will take a look this evening. Sorry for the delay

**Comment by Dwaynekj** [comment]
@juliuszc Just wanted to update you. I spent some time looking into today. I'll have an estimate of when we expect to have a fix. Thx!

**Comment by juliuszc** [comment]
@Dwaynekj Thanks a lot for taking a look. If you need any more information or if there is some way I can help let me know!

**Comment by Dwaynekj** [comment]
@juliuszc Here's a (fork)[http://codepen.io/Dwaynekj/pen/LkjZJk?editors=0110] that you can study. 

I turned off your force update
Added CSS for your grid target div (namely position relative and a fixed height)
Added overflow:hidden on line 55

**Comment by juliuszc** [comment]
@Dwaynekj The force update was just to show that it constantly resizes when columnAutoSize is set to true and the data updates. It does seem to respect the height with position relative and a set height, but it still overflows the width. Is that intentional?

**Comment by Dwaynekj** [comment]
I'm not seeing the width overflow. Can you refresh?

**Comment by juliuszc** [comment]
I edited the pen. Would you mind doing this over gchat?

**Comment by Dwaynekj** [comment]
Its a bit late today. We can do next week if needs be

You removed the container that had overflow hidden.

Simply add 
```
#asd {
  border-color: green; 
  border-style: solid;
  height: 200px;
  width: 200px;
  position: relative;
  overflow: hidden;
}
```

in your css

**Comment by juliuszc** [comment]
Right, but the grid is still overflowing the container. Shouldn't it respect the width set for it?

**Comment by Dwaynekj** [comment]
Ah, I see what you mean. The width doesn't inherit from the parent, but is set on the canvas as an inline property based on `HiDPI` settings.

**Comment by juliuszc** [comment]
Ok, thanks for the clarification.
