### ISSUE TITLE
Custom header name

### ISSUE THREAD

**Issue by RaghavPro** [openfin/fin-hypergrid#189]
How do you set custom header name?
I looked around the source code but found nothing.

**Comment by Dwaynekj** [comment]
Hey @RaghavPro Sorry for the delay. I also see that you responded on Skype.

Can you try setting the name of the column like so `column.header = 'xxx'`

**Comment by RaghavPro** [comment]
Thanks for replying @Dwaynekj.
I think I did tried setting header in `setColumnProperties`. Didn't work though. Is that how you do it?

Anyway, anything on #186?

**Comment by Dwaynekj** [comment]
To be more explicit.

```
grid.behavior.getColumn(COLUMN_INDEX).header = "test"
grid.repaint()
```

LMK

**Comment by RaghavPro** [comment]
@Dwaynekj 
How come this doesn't work?
`behavior.setColumnProperties(idx[columnName], {header: 'test'});`
