### ISSUE TITLE
"Undefined is not a function" at `flags.log.split`

### ISSUE THREAD

**Issue by efurmantt** [openfin/fin-hypergrid#19]
When running the examples (tt, twohundred, standalone - I didn't test the others) I see this error in the console, which seems to expect `flags.log` to be a string.

**Comment by osbert-messerfs** [comment]
Think it is related to [this issue](https://github.com/webcomponents/webcomponentsjs/issues/180). I updated [mine](https://github.com/osbert-messerfs/hypergrid-mfs/blob/master/public/assets/webcomponentsjs/webcomponents.js#L29) and it works.

**Comment by stevewirts** [comment]
I'll get to this soon,  I need to move the other dependencies at the same time.
