### ISSUE TITLE
Wheel listener

### ISSUE THREAD

**Issue by juliuszc** [openfin/fin-hypergrid#194]
The scroll event listener doesn't fire when you try to scroll up and the scrollbar is already at the top and vice versa. I was also wondering how to go about disabling the default scrollbar functionality and turning off the fin-bars. 

Also the context-menu listener doesn't respect the stopPropagation().

This is the pen to show that the event doesn't fire.
http://codepen.io/juliuszc/pen/RRjVRV?editors=0110

**Comment by Dwaynekj** [comment]
@juliuszc Hey! Thanks for looking into these. I've created tickets in our system. Please note that we are already in the middle of a sprint and have them prioritized after we get through our current queue. Expect an update for next week

**Comment by juliuszc** [comment]
@Dwaynekj Just to clarify, the order that the events are handled are: 
1. On grid initialization there are event listeners attached to the actual canvas.
2. When the event from the canvas fires, the event is decorated with information from the grid.
3. It's delegated to the behavior(what does the behavior do with this?)
4. A synthetic event is fired back to the user.

So if I wanted to add a completely new event, fin-wheel-moved, I would just have to create a new FireSyntheticWheelMovedEvent?

**Comment by Dwaynekj** [comment]
Correct on all points.

For point 3. Behavior can decide if it wants the feature [chain](https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern) to handle the event

**Comment by RaghavPro** [comment]
@juliuszc No, that won't do it.
You will need to do it by setting `columnIndexes` state. Like showed in demo app.

Here's how you will do it.
```
const idx = behavior.columnEnum;
grid.setState({ columnIndexes: [idx['symbol'], idx['name']] });
```

**Comment by juliuszc** [comment]
@RaghavPro Thanks! I'll try it out.

**Comment by juliuszc** [comment]
@Dwaynekj Is there any existing functionality to make one side of a cell border thicker than the others or do I have to extend my own cellRenderer?

**Comment by Dwaynekj** [comment]
Hey @juliuszc The cell borders are not styled on a per cell basis. For performance reasons they are painted after the cells are drawn https://github.com/openfin/fin-hypergrid/blob/master/src/lib/Renderer.js#L498

**Comment by juliuszc** [comment]
@Dwaynekj Thanks for the help. I ended up just creating a cell Renderer and drawing the line myself. I had a question about the decision to render the entire grid every time. Is it because it easier than comparing the old values and seeing if it needs to be re-rendered? I did a little performance test and the average time of re-render is about 7.5 ms, which is a bit high.

**Comment by juliuszc** [comment]
@Dwaynekj Would it be easy to pass in the values that are requiring a repaint? I wanted to see if I can optimize the re-rendering of the grid so that it only updates the necessary cells, instead of repainting the entire thing.

**Comment by Dwaynekj** [comment]
@juliuszc I'm not sure canvas can do partial repaints (its an all or nothing operation). @joneit correct?

**Comment by juliuszc** [comment]
@Dwaynekj It's possible. Instead of clearing the whole canvas like it's currently done, it would need to be changed to clearing rectangles that need to be changed and repainting those. Also thinking that since the grid lines don't change 90% of the time, there could be a second canvas who just paints the grid lines.

**Comment by Dwaynekj** [comment]
Ah I see. If its possible. Would you want to try to implement that? We don't have the time at the moment to explore this. I can point in you right direction of the code and offer guidance/screen sharing sessions/etc.

**Comment by Dwaynekj** [comment]
Hey @juliuszc I'm aware your working on https://github.com/openfin/fin-hypergrid/issues/291.

If you do come up with a new design for doing canvas painting and/or gridlines feel free to open a PR
