### ISSUE TITLE
Feature: fully disable scrolling

### ISSUE THREAD

**Issue by slikrik98** [openfin/fin-hypergrid#21]
I would like to be able to disable scrolling altogether. There is a use case we have where we will have a partially visible row at the bottom:

![image](https://cloud.githubusercontent.com/assets/1585478/6645693/af82648c-c98c-11e4-9d5b-dc6dab089002.png)

We don't want this grid to be scrollable at all (we handle all scrolling with the underlying data model).

**Comment by stevewirts** [comment]
Ok
:)

**Comment by stevewirts** [comment]
its now a configuration option
https://github.com/openfin/fin-hypergrid#modifying-various-hypergrid-features-and-property-defaults
