### ISSUE TITLE
develop build broken!

### ISSUE THREAD

**Issue by ColinEberhardt** [openfin/fin-hypergrid#223]
Regarding #215 - I rebased onto `develop` as requested, but couldn't re-test the commit because the branch will not build. The first issue is here:

https://github.com/openfin/fin-hypergrid/blob/develop/src/Shared.js#L10

Although on resolving this I hit a few other issues, but didn't continue digging ;-)

**Comment by Dwaynekj** [comment]
@joneit I thought we removed that

**Comment by joneit** [comment]
@Dwaynekj This is why we should have published an intermediate version of hyper-analytics, to accommodate treeview changes. I will do that now; and update Shared.js as well.

**Comment by joneit** [comment]
Shared.js has been updated. (Requires `npm update hyper-analytics`.)

**Comment by joneit** [comment]
@ColinEberhardt `develop` is good now. We will endeavor in future to make sure it is always left in a buildable/functional state. We shall also take under advisement your suggestion to make `develop` the default branch! Sorry to have wasted your time here. We are on a learning curve with git flow and managing an open source project. J.

**Comment by ColinEberhardt** [comment]
No worries - one thing that would certainly help is to set up a CI build, Travis for example.

**Comment by Dwaynekj** [comment]
Yes!
