### ISSUE TITLE
IE11 and Edge doesn't display a grid

### ISSUE THREAD

**Issue by bahrus** [openfin/fin-hypergrid#227]
Getting this error in edge:

SCRIPT5022: SyntaxError
FilterTree.js (116,1)

**Comment by Dwaynekj** [comment]
@bahrus Hey! Sorry for the delay in getting back to you. We were away on holiday.
 Thanks for pointing this out. We will address this soon and have full support for the evergreen browsers

**Comment by Dwaynekj** [comment]
To further elaborate. The filtering module will get externalized from HyperGrid Core and be used as add-on as described [here](https://github.com/openfin/fin-hypergrid#the-filtering--analytics-sorting--aggregation-modules-provided-will-be-broken-out-of-hypergrid)

Its one our major goals for this summer

**Comment by allanelder** [comment]
I also saw an issue on IE; namely that this line (16962) in the typeOf function fails as the name property is undefined. 

return something.constructor.name.toLowerCase();

This [jsfiddle](http://jsfiddle.net/d6r3g/) shows the issue.

**Comment by Dwaynekj** [comment]
@allanelder Ah ok. Thanks will note that as well

**Comment by Dwaynekj** [comment]
PR is being reviewed https://github.com/openfin/fin-hypergrid/issues/227

**Comment by Dwaynekj** [comment]
PR's for fixing the bootstrapping on IE are merged. Note however that their are still some lingering IE bugs to be fixed.
