### ISSUE TITLE
Useless image increases build size

### ISSUE THREAD

**Issue by jjrv** [openfin/fin-hypergrid#231]
The file `images/Hyperblotter Tabled Reduced Rows.png` gets built by Gulp for example into `demo/build/fin-hypergrid.min.js` and the distribution package at `https://openfin.github.io/fin-hypergrid/build/fin-hypergrid.min.js`. Removing the png file shrinks the minified build from 395407 to 335683 bytes (15% space savings).

**Comment by jjrv** [comment]
Never mind, it seems this is already fixed in the `develop` branch.

**Comment by Dwaynekj** [comment]
Thanks for noting
