### ISSUE TITLE
Unable to load fin-Hypergrid in GoldenLayout component

### ISSUE THREAD

**Issue by RajeeNedunchezhian** [openfin/fin-hypergrid#239]
Hi,
I keep getting some errors while trying to load fin hypergrid in goldenlayout component. 
Please can you help.
[http://stackoverflow.com/q/38787498/887701?sem=2]

Thanks and Regards,
Rajee
[exampleGoldenLayout.txt](https://github.com/openfin/fin-hypergrid/files/403616/exampleGoldenLayout.txt)

**Comment by Dwaynekj** [comment]
@RajeeNedunchezhian Hello!

The Hypergrid constructor expects a DOMElement (particular a div). `this._hyperGridcontainer.getElement()` seems to be returning a wrapper object around a div that is used internally by the golden layout component

**Comment by Dwaynekj** [comment]
As a quick hack try `this._hyperGridcontainer.getElement()[0]`

**Comment by Dwaynekj** [comment]
Closed due to inactivity
