### ISSUE TITLE
Feature: Frozen columns

### ISSUE THREAD

**Issue by eduardotang** [openfin/fin-hypergrid#25]
it would be nice to have, thx

**Comment by stevewirts** [comment]
you can do fixed columns and fixed rows,  there are functions on the behavior object called getFixedColumnCount and getFixedRowCount with corresponding getFixedColumnValue(x, y) and getFixedRowValue(x, y), these can be replaced/overridden manifesting with fixed rows/columns.

If there is a better API please let me know.
 :)
-steve

**Comment by stevewirts** [comment]
you can do fixed columns and fixed rows,  there are functions on the behavior object called getFixedColumnCount and getFixedRowCount with corresponding getFixedColumnValue(x, y) and getFixedRowValue(x, y), these can be replaced/overridden manifesting with fixed rows/columns.

If there is a better API please let me know.
 :)
-steve

**Comment by eduardotang** [comment]
it would be good if you can add an example

**Comment by stevewirts** [comment]
done :)

https://github.com/openfin/fin-hypergrid#fixed-columns-and-rows

**Comment by eduardotang** [comment]
thanks very much : )  , a very nice grid control indeed, i have been looking at ExtJs, jqgrid, and some react grid, none of those can compare when it comes to very frequent update on data.

is sorting possible on these fixed columns? if so, hope u can do me a last favor, add it to the example as well. really appreciate

**Comment by eduardotang** [comment]
and also, can grid state include the fixed columns as well?

**Comment by stevewirts** [comment]
do you mean if you click on the fixed column header it sorts the rows
according to the data in the fixed column?

**Comment by stevewirts** [comment]
sure, give me a day or so to get this in......

**Comment by eduardotang** [comment]
yeah, i would like them to behave just like other normal columns, but just frozen to the left when your scroll right.....

**Comment by stevewirts** [comment]
hi this is done, try it now....

https://github.com/openfin/fin-hypergrid#fixed-columns

**Comment by eduardotang** [comment]
really thx so much for the quick response, very good job,
 looking forward to the filter and grouping, have you guys got a targeted timeline for those?

**Comment by stevewirts** [comment]
Theres a solution thats almost ready that would require using q
The benefit is that you can handle million row data sets and obscene update
rates

That will be ready in a few days
The javascript solution will be another week or two
Im exploring using webworkers to push the performance

**Comment by eduardotang** [comment]
awesome !!, looking forward to your good news

**Comment by eduardotang** [comment]
HI,

is the new release ready yet?
i am longing for the filter and grouping feature
thx

**Comment by stevewirts** [comment]
Hi,
I should have something by end of next week....
thanks
-steve

**Comment by eduardotang** [comment]
awesome, thx
