### ISSUE TITLE
Context Menu Listener does not respect StopPropagation

### ISSUE THREAD

**Issue by Dwaynekj** [openfin/fin-hypergrid#252]
Originally Reported [here](https://github.com/openfin/fin-hypergrid/issues/194)

**Comment by juliuszc** [comment]
@Dwaynekj I fixed this as well. Just need to add an event.stopPropagation() on like 76 in Hypergrid.js

**Comment by Dwaynekj** [comment]
Awesome! Do you want to add a PR to develop?

**Comment by Dwaynekj** [comment]
@juliuszc Just checking in here
