### ISSUE TITLE
Scroll Event Not Firing

### ISSUE THREAD

**Issue by Dwaynekj** [openfin/fin-hypergrid#253]
Originally Reported [here](https://github.com/openfin/fin-hypergrid/issues/194)

**Comment by juliuszc** [comment]
@Dwaynekj  This is actually a bug stemming from the fin-scrollbars component. I think the current behavior of scroll is right. It should only fire when the scrollbar moved. I ended up adding a mouse-wheel listener and subscribing to that.

**Comment by Dwaynekj** [comment]
@juliuszc I see ok. I'll close this issue
