### ISSUE TITLE
Make Scrollbars hideable (such as when the grid has no rows)

### ISSUE THREAD

**Issue by Dwaynekj** [openfin/fin-hypergrid#254]

**Comment by RaghavPro** [comment]
hey @Dwaynekj 
I would like to do this. If you can guide me a bit.

**Comment by RaghavPro** [comment]
The above mentioned commit fixes it I think. Have a look and let me know.

**Comment by Dwaynekj** [comment]
Hey @RaghavPro Thanks for picking this up!. @joneit and I plan on reviewing it later this week

**Comment by Dwaynekj** [comment]
@RaghavPro Is there anyway you can make this a configurable options using src/defaults.js. Like say 
`showScrollBars: true`

**Comment by RaghavPro** [comment]
@Dwaynekj Can do that but what's the point of scroll bar when there's no data to scroll? I don't think it should be a configurable option. Can be done though.

**Comment by RaghavPro** [comment]
@Dwaynekj Have you reviewed this? Let me know what more needs to be done.

**Comment by Dwaynekj** [comment]
@RaghavPro Yes. Our next sprint release is in 2 weeks. We operate on 3 week cycles, we will address this before then

**Comment by Dwaynekj** [comment]
@RaghavPro Before @joneit And I can merge this we've have to test out if the scroll bars are being hidden when there is no point to scrolling. We will have to test this first

**Comment by RaghavPro** [comment]
@Dwaynekj Of course. I still have to send the PR. I wasn't sure about the branch.

**Comment by Dwaynekj** [comment]
Hey @RaghavPro We decided to punt on this for now. We had some major refactoring done that fixed this as well.

Sorry to have waste your time and do we want to have you apart of Hypergrid as we move forward. We're going to be adding more tickets to our github issues or potentially a public Jira to make this workflow easier and avoid overlap
