### ISSUE TITLE
Negative rows appear when pressing down arrow after scrolling

### ISSUE THREAD

**Issue by mrbedo** [openfin/fin-hypergrid#26]
To repro:
1. Go to the demo page: http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/demo.html
2. Grab the right scroll bar's thumb and drag it down.
3. Press the down arrow key.

![negative row](https://cloud.githubusercontent.com/assets/8764565/7147227/70710510-e2c7-11e4-8d3e-660bb9111000.png)

**Comment by stevewirts** [comment]
fixed thanks!
