### ISSUE TITLE
Inline editing only works once if you are not using Chrome

### ISSUE THREAD

**Issue by apm** [openfin/fin-hypergrid#27]
Trying out your example site on OSX 10.10.2, and both Safari 8.0.4 and Firefox 37 (and 38b5) show the edit control once when double-clicking on a cell.  The second attempt provides a silent failure.  Chrome works fine.

Firefox also has a couple more issues:
- The column headers are black on black.
- No cell borders
- Cells are white instead of grey

**Comment by stevewirts** [comment]
thanks,  I'll get right on these.....

**Comment by stevewirts** [comment]
I've fixed the editor issue.  Can you provide any more details for the
final 3 issues from above, I can't seem to reproduce them.

**Comment by apm** [comment]
Thanks @stevewirts, all of the symptoms in Firefox went away on the main example site.  The standalone json example running on my local machine still has the display issues in Firefox (but a fresh bower install did indeed fix the cell editing problems).

![firefox-osx-hypergrid-freshprofile](https://cloud.githubusercontent.com/assets/38468/7273811/fc64cfae-e8ab-11e4-8e51-6ec63df30454.png)

One other thing I noticed, and this may be intentional: in the json example, the date column has a combo spinner control/calendar panel overlay.  Neither Firefox nor Safari display these widgets when editing.

**Comment by stevewirts** [comment]
great, I'll dig out the problem today, thanks for finding this.

**Comment by stevewirts** [comment]
fixed, thanks!

**Comment by apm** [comment]
Thanks, looks good.
