### ISSUE TITLE
Grid doesn't render in Safari on Mac or IPad

### ISSUE THREAD

**Issue by baalazamon** [openfin/fin-hypergrid#272]
Grid doesn't render in latest version of Safari on Mac or iPad. It does not  throw any errors.

**Comment by Dwaynekj** [comment]
@baalazamon Thanks for noting this. I'll keep this issue open. We hope to resolve the issues on the evergreen browsers by the end of summer

**Comment by Dwaynekj** [comment]
This should handle desktop safari https://github.com/openfin/fin-hypergrid/pull/296

Mobile support is a longer term goal

**Comment by Dwaynekj** [comment]
Fixes merged into 1.0.9
