### ISSUE TITLE
Can't get basic JSON example to work

### ISSUE THREAD

**Issue by SukumarMehta** [openfin/fin-hypergrid#280]
Hi - I'm guessing that I'm not including the proper js, but following the example-fin-hypergrid-behavior-json js, I can't get my simple case to work.

What I'm trying to do: open a websocket, and onmessage set the JSON payload to a grid.  That's it.   I have the websocket connection, I get a valid JSON, but I can't get it to stick to a hypergrid.  How can I do this? This should be 1 line of code but it seems really complicated. 

I've tried to follow the jsonGrid -> jsonModel via getBehavior() - after defining a <fin-hypergrid-behavior-json> element, however, I can't get past the simple jsonModel instantiation

`<script src="https://openfin.github.io/fin-hypergrid/build/fin-hypergrid.js"></script>`
`<fin-hypergrid id="json-example">`
`	<fin-hypergrid-behavior-json></fin-hypergrid-behavior-json>`
`</fin-hypergrid>`
...
`var jsonGrid = document.querySelector('#json-example');`
`var jsonModel = jsonGrid.getBehavior();`

`ERROR: Uncaught TypeError: jsonGrid.getBehavior is not a function`

Also - not sure if you guys are aware but all of the JSON example links in the README point back to the README - so they don't really help

**Comment by Dwaynekj** [comment]
@SukumarMehta Hey I see your using our de-polymerized version build of hypergrid with a workflow that depends on the old polymer version.

The build for polymer is located here https://github.com/openfin/fin-hypergrid-polymer-demo/tree/gh-pages/components/fin-hypergrid/demo/build

Please note that we no longer support the polymer version and the focus concentrates on the non-polymer version

**Comment by SukumarMehta** [comment]
@Dwaynekj Thanks for the explanation

1. The link you provided seems to be a dead-link?
2. How would I achieve this use case with the non-polymer version?  Is there documentation for this?

**Comment by Dwaynekj** [comment]
The link works now, the repo was accidentally private.

For details on how to work with the new version of hypergrid, you can checkout our readme
https://github.com/openfin/fin-hypergrid

**Comment by SukumarMehta** [comment]
Thanks - ok I see what you mean now.

`var grid = new fin.Hypergrid('#fin-grid', { data: data });`

This construct works - but I have 2 questions:

1. Is there a way to update the data object in an existing grid?  Ideally I would like to declare a new Hypergrid on startup, and simply update the data onmessage().  I tried to instantiate a new grid on every message, which works, but the rendering is weird - it doesn't seem to clear the grid before repainting, and I can't seem to find a repaint function which fixes this. So...

2. in the scenario where the first grid is 3x3 and the second grid (on update message) is 2x2 - declaring a new Hypergrid() doesn't wipe out the excess 3rd column and 3rd row - it's still visible.  How can I clear this area?  I've tried paint() - paintNow() - behaviorShapeChanged() -etc.. and none seem to work.

Thanks

**Comment by Dwaynekj** [comment]
@SukumarMehta This area is something that we currently revising as we plan to reintroduce support for remote behavior. I will have an update for you by end of tomorrow

**Comment by Dwaynekj** [comment]
@SukumarMehta Support for remoting will come about over the coming weeks, it certainly won't be complete by the end of our sprint next week. However, our plan is to produce apis that will enable you to implement a remote functionality and allow you to provide feedback on what else you need to enable something like realtime updates (i.e. an iterative process).

So with regards to your requests to update data and removing certain rows. Look for an initial api release to help enable you in the coming weeks

**Comment by SukumarMehta** [comment]
Thanks - will do

**Comment by noahtaylor** [comment]
@Dwaynekj has this been released in v1.0.9?

**Comment by Dwaynekj** [comment]
@noahtaylor The first iterations is slated for the very next release (originally intended for this coming Monday, but now we are aiming for the following Monday).
