### ISSUE TITLE
2 grids on same page

### ISSUE THREAD

**Issue by SukumarMehta** [openfin/fin-hypergrid#282]
Hi, don't mean to pile on here, but it seems like having anything other than 1 hypergrid on a page is not supported?

I have tried to put more than 1 grid on the same page, or even other components like buttons or text-boxes.  I've used `<div>`, `<panel>`, `<container>`, etc... as separators, but it seems like the last painted **always** snaps to the abosolute top-left position on the page and deactivates all other components (while not actually painting over the excess areas).  How can I achieve this?  The only example on the README page has 1 grid and nothing else.

Apologies if this is the same underlying issue as the one I reported yesterday.

**Comment by Dwaynekj** [comment]
Hey @SukumarMehta Can you try placing the div target for the grid in a element with position relative.
I'm assuming the non-polymer HyperGrid version

**Comment by SukumarMehta** [comment]
I am using the non-polymer version

I assume you mean something like this?

old `<div id="fin-grid"></div>`
new `<div id="test" style="position: relative;"><div id="fin-grid"></div></div>`

it causes the grid to not be rendered at all - am I missing something?

**Comment by Dwaynekj** [comment]
Try something like this

```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
    </head>
    <body>

    <div id="fin-grid" style="position:relative; height: 300px;"></div>
    <div id="fin-grid2" style="position:relative; height: 300px;"></div>

    <script src="https://openfin.github.io/fin-hypergrid/build/fin-hypergrid.min.js"></script>

    <script>
var data = [
    { symbol: 'APPL', name: 'Apple Inc.', prevclose: 93.13 },
    { symbol: 'MSFT', name: 'Microsoft Corporation', prevclose: 51.91 },
    { symbol: 'TSLA', name: 'Tesla Motors Inc.', prevclose: 196.40 },
    { symbol: 'IBM', name: 'International Business Machines Corp', prevclose: 155.35 }
];

var grid = new fin.Hypergrid('#fin-grid', { data: data })

grid.addProperties({
    showRowNumbers: false,
    showFilterRow: false
});

var grid2 = new fin.Hypergrid('#fin-grid2', { data: data })

grid2.addProperties({
    showRowNumbers: false,
    showFilterRow: false
});
</script>
</body>
</html>
```

**Comment by SukumarMehta** [comment]
Thanks - ok that seems to work.  I've also managed to get it work with the 2 grids side by side.  'height' %s don't work, it has to be in absolute px but I can live with that.  The only challenge is the scrolling of overflow.  Is there documentation of the available grid properties/ what they are and what they mean?  I'm digging through the code at this point and it's proving to be difficult.

For example, I have a table with 100 elements, the scroll wheel goes to the bottom of the table with the minimum wheel rotation.  to scroll through i have to drag the scroll bar on the right.  So, any documentation re: options/properties that could help me tweak the behavior would be great.

Thanks

--
Sukumar

**Comment by Dwaynekj** [comment]
The list of grid properties can be found here.

http://openfin.github.io/fin-hypergrid/doc/module-defaults.html

Thanks for noting the issue with the Scroll Wheel. We'll look to make it more configurable in the next sprint
