### ISSUE TITLE
Ability to hide fin bars

### ISSUE THREAD

**Issue by Dwaynekj** [openfin/fin-hypergrid#291]
Referenced here https://github.com/openfin/fin-hypergrid/issues/194

**Comment by juliuszc** [comment]
@Dwaynekj I can do this because I already did it for my own use. Also, I would need to change the finbars to allow propagation of the wheel event so that a user can subscribe to the wheel event.

**Comment by Dwaynekj** [comment]
All yours!

**Comment by Dwaynekj** [comment]
I'll close this. We will be releasing a WIKI of how to do so for this sprint

**Comment by joneit** [comment]
Resolved by **Hypergrid v2.1.11** (PR #722).
