### ISSUE TITLE
Re-Introduce Hypergrid Theming

### ISSUE THREAD

**Issue by unclepaul84** [openfin/fin-hypergrid#297]
It would be awesome if one could configure the  grid to pull in Bootstrap  table, th, tr, td  styles....

**Comment by Dwaynekj** [comment]
Hey @unclepaul84 Sorry for the delay!

To be clear, you want to style Hypergrid to look like a bootstrap table?
The grid has the ability to reference a style guide/theme. However, there is some refactoring that needs to be done as it was originally made to reference Polymer Elements.

**Comment by unclepaul84** [comment]
Yes. So by just flipping a config property ti would read the styles of
bootstrap css that are in context.

Another idea i had was to make a generator. One would feed it bootstrap.css
and it would generate  theme json object that can applied to the grid...
(this is what i basically did manually this time around)

Thanks

**Comment by unclepaul84** [comment]
Does grid support alt-row color? It tried backgroundColor2, but it does not
work

Thanks

**Comment by Dwaynekj** [comment]
Hey,
You would have to enable that programmtically by overriding the getCell method like seen here
https://github.com/openfin/fin-hypergrid/blob/master/demo/js/group-view.js#L46
and here https://github.com/openfin/fin-hypergrid/blob/master/demo/js/group-view.js#L53

to something like so 

```
    function getCell(config, rendererName) {
        if (isOdd(config.x)) {
            config.backgroundColor = '#e8ffe8';
        } else {
          config.backgroundColor = 'white';
        }
       return grid.cellRenderers.get(rendererName);
    }
```

Further documentation can be found [here](http://openfin.github.io/fin-hypergrid/doc/tutorial-cell-renderer.html). The tutorial is very new, so let us know if you have any advice on how to improve it!

**Comment by unclepaul84** [comment]
Thanks.

As far as quality of samples , my feedback is as follows. In my humble
opinion, main demo.js  sample is overwhelming. These is too much supporting
code to go thru before actually getting to API code. It think it needs to
be split up into feature based sub samples. I believe good samples are
critically important for adoption. I would suggest looking at how plotly.js
does their documenting for a good start(my favorite feature is "run on code
pen").

If you guys come up with the framework for documenting, i will be willing
to write some samples.

**Comment by Dwaynekj** [comment]
@unclepaul84 I received your email and forwarded it support@openfin.co which for Hypergrid will be handled by @joneit and myself.

We totally agree on making smaller examples for our tutorials. Also note that we are migrating them from jsdocs and into Github Wiki for easier accessibility

**Comment by Dwaynekj** [comment]
@unclepaul84 Wanted to provide an update that our first set of getting started wikis will be pre-releases this week, in-tandem with the end of our sprint cycle. 

With regards to making Hypergrid themable, we have created a ticket in our internal log which we hope to get to late September/early October (as in being included as apart of one the next couple of sprints).

Let us know if you have any concerns!

**Comment by Dwaynekj** [comment]
@unclepaul84 We made some good progress on re-adding theming support. Currently we have it on pause for the active sprint, but its on deck for our late Feb-March Sprint

**Comment by prabhur1983** [comment]
HI ,

Are themes supported now ? I need to apply themes on the grid ..

**Comment by Dwaynekj** [comment]
@prabhur1983 I see you opened a similar ticket, I'll respond there

**Comment by Dwaynekj** [comment]
An a initial wiki on theming is now available https://github.com/openfin/fin-hypergrid/wiki/Themes
