### ISSUE TITLE
Extend cell renderer 

### ISSUE THREAD

**Issue by juliuszc** [openfin/fin-hypergrid#308]
How should I import the cellRenderer so that I can extend it? Also that part of the docs is a bit outdated because the sparkStarRenderer uses functions that don't exist anymore.

**Comment by Dwaynekj** [comment]
@juliuszc Thanks for noting, as we move the docs to the github wiki, I'll be sure to update.

In any case to create your own renderer you can do the following.
```
   //Extend HyperGrid's base Renderer
   var base = grid.getCellRenders.get('EmptyCell').constructor
   myRenderer = base.extend(//Your code here//)
   grid.cellRenderers.add('alias', myRenderer)

   //Which you can then load into your override getCell
   grid.behavior.dataModel.getCell(config, renderName){
     if (config.x === 0) {
        rendererName === 'alias'
     }
      //return the default render
      return grid.cellRenderers.get(rendererName);
   }
```

**Comment by juliuszc** [comment]
Just in case someone is looking at this in the future.
let base = this.grid.cellRenderers.get('EmptyCell').constructor
