### ISSUE TITLE
Grid State

### ISSUE THREAD

**Issue by unclepaul84** [openfin/fin-hypergrid#309]
Is it possible to save Filters, sort  and column order to json string?  grid.getState/setState does not seem to work...

**Comment by Dwaynekj** [comment]
@joneit Can offer some assistance here

**Comment by unclepaul84** [comment]
This may be related to #310. Same error is produced when calling setState...

**Comment by Dwaynekj** [comment]
Ah Ok. We'll have an update for you before the end of the week

**Comment by Dwaynekj** [comment]
@unclepaul84 Sorry for the delay here. We've confirmed the bugs and have added them to our backlog. We will be triaging them next week. Let us know if this is affecting/blocking you significantly

**Comment by unclepaul84** [comment]
Currently, It is not affecting us significantly.  But i want to reiterate
that saving grid state should be well flushed out as it is critical
functionality in a finance app.

**Comment by Dwaynekj** [comment]
from @joneit 

Submitted [PR 403|https://github.com/openfin/fin-hypergrid/pull/403] which includes:
* added dynamicProperties.js
* reduced number of layers of grid props cascade from 5 to 2:
** defaults (aka globalProperties), developer can mutate with global settings and global theme
** grid.properties for individual grid settings and theme
* dynamic properties are getter/setters that sit in grid.properties and initialize themselves with values from defaults
* moved grid properties initialization from Behavior.js to Hypergrid.js (this makes it available before Behavior instantiated)
* moved clearState from Behavior.js to Hypergrid.js; the former now calls the latter
* removed call to clearState from Behavior.js's setData
* moved buildTheme function to its own file (not currently being called)
* corrected misspelling in noDataMessage property

**Comment by Dwaynekj** [comment]
from @joneit 

I moved `columnProperties[]` from `grid.properties` and added it to the `Column` object as simply `properties`. `Behavior..getDefaultState()`, which previously `Object.created `a new object based on `grid.lnfProperties` with `columnProperties[]` added to it, now returns simply `grid.lnfProperties`. (For now. We will be doing further streamlining with this ticket.)

If this is merged to develop before you start, no issue. But if you want to do it in parallel, you should make the same changes: Look at this https://github.com/joneit/fin-hypergrid/commit/7adfa9ce0c505a2c8c087cbee6be37fd38bdcd9d (ignoring `demo/row-props.html` and `src/lib/Renderer.js`). I can supply a patch file.

**Comment by Dwaynekj** [comment]
# Hierarchy

- All Grids: fin.Hypergrid.globalProps = defaults.js
-    setTheme a shell function to be implemented that will mutate this
- Singular Grid properties 
-   grid.properties will replace lnf properties and defaultState and will be based off .globalProps
-   grid.setState/options.state will replace wholesale grid.properties
-   clearState will recreate grid.properties from .globalProps (some properties supposedly should not be clobbered)
-   noExportProperties, and other junk
-   setTheme/options.theme and in HG constructor

  
## Column properties

-   Column props off the column object (not hanging it off default state) which will derive its information from the schema 
-    setColumnProperti(es) implementation may have to change
-    column order
-  hidden columns

## Cell properties 

- Row Properties
- Cells (conditionally reapplied after getCell)

**Comment by joneit** [comment]
h4. State

State should include:
* version — shall refer to a specific json parser
* flattened grid state as described by defaults.js
* column props — shall be a sub-hash under the key `column` wherein individual columns are keyed by column name and the value is a sub-sub-hash that overrides other properties
* row props — shall be a sub-hash under the key `row` wherein individual rows are keyed by row number and optional subgrid name. The only row property we currently support is height.
* cell props — shall be a sub-hash under the key `cell` wherein individual cells are keyed by column name, row number, and optional subgrid name and the value is a sub-sub-hash that overrides other properties. Specifying more than a handful of these triggers a warning. (The threshold is itself a property.)

#### Registered objects

Properties may reference by name certain "registered objects" (objects previously added to a dictionary) such as:
* cell renderer — already implemented as `renderer`
* grid renderer — already implemented as `gridRenderer`
* data pipeline — however we intend to remove references to pipeline (GRID-410)
* subgrids — currently defined in src/bnehaviors/subgrids.js::`defaultSubgridSpecs`
* calculators — for computed cells/columns

#### Hierarchical datagram

We also would like to revisit introducing a hierarchical structure for props currently defined as flat but with lengthy (and inconsistent!) names. For example, prop currently dereferenced as `defaults.columnHeaderForegroundSelectionColor` could instead be dereferenced as `columnHeader.selection.color`. For backwards compatibility, we would still accept the flattened names, throwing an error if both are specified.

**Comment by Dwaynekj** [comment]
@joneit Should I delete my comment from 26 days ago?

**Comment by Dwaynekj** [comment]
https://github.com/openfin/fin-hypergrid/wiki/Persisting-Grid-State
