### ISSUE TITLE
Filtering api broken in 1.0.10

### ISSUE THREAD

**Issue by unclepaul84** [openfin/fin-hypergrid#310]
When i grab state of filters and then set it right back i get 
![image](https://cloud.githubusercontent.com/assets/2429062/18106043/7a9e7526-6ec7-11e6-98f6-0aabd22b7ac4.png)

Here is the code:

```
        var state = grid.getGlobalFilter().columnFilters.getState();

        console.warn("filter state", state);

       grid.getGlobalFilter().columnFilters.setState(state);

       grid.behavior.updated();
```

Furthermore, i followed sample for setting column filter from code and it results in the same error.

Please advise

**Comment by Dwaynekj** [comment]
@joneit Can offer some assistance here

**Comment by Dwaynekj** [comment]
@unclepaul84 Sorry for the delay here. We've confirmed the bugs and have added them to our backlog. We will be triaging them next week

**Comment by Dwaynekj** [comment]
FilterTree has been removed from Hypergrid Core
