### ISSUE TITLE
various state issues on row selection highlight

### ISSUE THREAD

**Issue by wmira** [openfin/fin-hypergrid#321]
There seems to be a weird behavior here. See this example...

1. Click a cell. You would notice that the row isn't highlighted
2. Now tick on aggregates on grouping. Notice that after checking aggregates, clicking a cell highlights a row.
3. Now untick/uncheck aggregates. I assume the behavior should be as per 1. but it is not. Clicking a cell now selects a row.

there is the same weird behavior when clicking on "by row handles only".

What I really want just to happen is, how can I get the behavior on selecting the entire row when clicking a cell? The state of the grid seems to be somewhat inconsistent or something is broken as setting various attributes breaks the state.

**Comment by Dwaynekj** [comment]
@wmira Thanks for pointing this out! It turns out this is an issue with our main demo (which has gotten unwieldy and is not very exemplary). We are transitioning away from it to a a group of simpler tutorial/examples

To get the behavior you want simply do Hypergrid.addProperties({'checkboxOnlyRowSelections': false})

**Comment by wmira** [comment]
@Dwaynekj  I thought checkboxOnlyRowSelections is defaulted to false? I'm assuming thats the default behavior (e.g. clicking a cell selects the whole row ) but it doesnt seem to work. https://github.com/openfin/fin-hypergrid/blob/72f70a5867a879b243b9b239596550be2a06f483/src/defaults.js#L657

**Comment by Dwaynekj** [comment]
Hey @wmira Sorry for the delay! Yes your correct it should default to false. How are you testing? Are you using our main demo or do you have your own Hypergrid instance?

**Comment by wmira** [comment]
Hi @Dwaynekj  yes but the basic example also should behave like when a row is clicked it is selected as well...  https://openfin.github.io/fin-hypergrid/example.html

**Comment by Dwaynekj** [comment]
@wmira With the original default in place can you try the following

```
 grid.addEventListener('fin-selection-changed', function(e) {

        //lets mirror the cell selection into the rows and or columns
        grid.selectRowsFromCells();
```

**Comment by Dwaynekj** [comment]
any luck?

If so I can incorporate into the grid

**Comment by wmira** [comment]
@Dwaynekj sorry I will try this today and get back to you.

**Comment by wmira** [comment]
@Dwaynekj thanks. the above code works. I tried it on the basic example. Closing.
