### ISSUE TITLE
Polymer 1.0 support

### ISSUE THREAD

**Issue by bjackson** [openfin/fin-hypergrid#33]
Is support planned for Polymer 1.0?

**Comment by stevewirts** [comment]
Absolutely
I dont have an eta yet though

**Comment by enf644** [comment]
Polymer 1.0 support is not stated in Road Map. 
Does it mean that we should not wait for support in near future?

**Comment by stevewirts** [comment]
Our currently path involves removing polymer.  We plan on plugging into
polymer after this though.

**Comment by enf644** [comment]
Removing polymer is not is roadmap either.
Does these means that you will do polymer removal after current roadmap is complete?
Maybe some rough eta?

**Comment by stevewirts** [comment]
Hi,

We've done a huge refactoring that's still not complete.  Take a look at the feature/big-refactoring branch.
We're approaching feature and API parity with the master branch.  When that is done, we will remove polymer.  Part of this piece of work is an analytics piece (stable multisorting, rollups+aggregations, grouping, filtering, etc...) that is mentioned in the roadmap.  I can't say exactly when this will get done as my priorities are driven by my company.  Right now I'd say maybe in a month we will push out this new version that should be polymer free, with analytics capabilities added.

hope that helps :)

~steve

**Comment by stevewirts** [comment]
Just for clarity, we had several groups request a polymer-free version.  With the fact we were really only using it for the eventing system and it's inheritance model we decided to move away from it.  We plan on "plugging" hypergrid in under polymer as well as other frameworks once it runs outside of polymer.

thanks for your interest and hope that clears up why were heading in that direction.

~steve

**Comment by enf644** [comment]
2 months have passed :(
Any ETA on polymer 1.0 support or polymer free version?

**Comment by stevewirts** [comment]
we are shooting for end of 4th quarter, it's an enormous amount of work,

**Comment by GanapathyRajalingam** [comment]
Hi Steve,

Any update as when we will be able to use finHyperGrid with Polymer 1.0?
Awaiting to use finHypergrid in our apps.

~Ganapathy.

**Comment by amamh** [comment]
I'm waiting for the refactor too. Currently, I'm using Polymer 1.0 and if I import hypergrid it seems to cause issues because it's using Polymer 0.5

Removing Polymer completely or upgrading to 1.0 would be great! Thanks for your efforts regardless :+1:

**Comment by Dwaynekj** [comment]
@amamh Polymer dependencies have been removed from the big-refactor branch
