### ISSUE TITLE
Specifying column names

### ISSUE THREAD

**Issue by noahtaylor** [openfin/fin-hypergrid#335]
I'm trying to pre-specify columns names within my hypergrid.  I want to initialise my grid as empty:
var grid = new fin.Hypergrid('#fin-grid', {data:[]});

then add elements into it as I receive them using:
var myModel = grid.behavior;
myModel.dataModel.addRow(record);
myModel.applyAnalytics();
grid.behaviorChanged();

The problem when I do this is my grid just stays empty.  The only way I can work around this is to initially enter a dummy entry with the fields I want then apply:
grid.behavior.getColumn(idx.ALIAS).header = "Alias";
to set the headers.  Is there a nicer way of doing this?  I also tried submitting a column list as part of the options on the hypergrid but this did not seem to recognise the names properly.

**Comment by Dwaynekj** [comment]
@joneit Can you respond?

**Comment by joneit** [comment]
Hello Noah,

This works for me:

var myFields = ['last_name', 'first_name', 'etc'];
myModel.setFields(myFields); // or...
myModel.setData({ data: [], fields: myFields });
myModel.dataModel.addRow({'last_name':'Jones', 'first_name':'Joe', 'etc':24});
myModel.applyAnalytics()

**Comment by joneit** [comment]
By the way, you can get better derived headers with (from demo.js):

var headerify = fin.Hypergrid.analytics.util.headerify;
headerify.transform = headerify.capitalize;
...
> grid.behavior.dataModel.getHeaders()
["Last Name", "First Name", "Etc"]

**Comment by joneit** [comment]
Noah,

Whoops, the above example was for the as yet unreleased dev version (1.1.0).

The following does however work on 1.0.10:

var myFields = ['last_name', 'first_name', 'etc'];
myModel.setFields(myFields);
myModel.dataModel.addRow({'last_name':'Jones', 'first_name':'Joe', 'etc':24});
myModel.applyAnalytics();
myModel.behavior.shapeChanged();

**Comment by Dwaynekj** [comment]
@noahtaylor Any luck?

**Comment by noahtaylor** [comment]
@Dwaynekj sorry been away from hypergrid dev for a few days, just tried this out and it worked thanks
