### ISSUE TITLE
Make a column invisible

### ISSUE THREAD

**Issue by noahtaylor** [openfin/fin-hypergrid#349]
I'm looking to make some of the Hypergrid columns invisible.  I couldn't find anything in the documentation except for vague references to column index = -1.  I tried manually setting the column index = -1 e.g. 
grid.behavior.getColumn(5).index = -1;
but this only cleared out any values in the column and left an empty column.  
Any advice on how to hide a column?

**Comment by noahtaylor** [comment]
This seems to work in hiding a column:
grid.behavior.columns.splice(5, 1);

**Comment by Dwaynekj** [comment]
@noahtaylor Hello,

That is correct.behavior.columns represents the list of visible columns while behavior.allcolumns represents all the the available columns.

Apologies for not documenting this. I will add a Wiki with some basic information on columns today. Please note that the we will iterate on them over the coming weeks
