### ISSUE TITLE
Adding event's not working

### ISSUE THREAD

**Issue by anuccio1** [openfin/fin-hypergrid#35]
when I call "addFinListener" on my grid, I get the following:

TypeError: jsonModel.addFinListener is not a function
    at tradeBlotterWidget.js:132
    at processQueue (angular.js:14454)
    at angular.js:14470
    at Scope.$get.Scope.$eval (angular.js:15719)
    at Scope.$get.Scope.$digest (angular.js:15530)
    at Scope.$get.Scope.$apply (angular.js:15824)
    at done (angular.js:10263)
    at completeRequest (angular.js:10435)
    at XMLHttpRequest.requestLoaded (angular.js:10376)

Just wondering if this functionality has maybe been renamed or changed?

code:

var jsonModel = jsonGrid.getBehavior();
 jsonModel.addFinListener('fin-click', function(event) {
       console.log(event);
});

**Comment by stevewirts** [comment]
Alex,
that's a bug in the documentation, the name had been changed(It's been
fixed), thanks, the function name is 'addFinEventListener', sorry 'bout
that.
-steve

**Comment by snackycracky** [comment]
also the listener shoud be called on the jsonGrid Object not on jsonModel in your example. 

```
var jsonModel = jsonGrid.getBehavior();
jsonModel.addFinListener('fin-click', function(event) {
console.log(event);
});
```
the correct code is:

```
var jsonGrid = document.querySelection('#json-grid');
    jsonGrid.addFinEventListener('fin-cell-click', function(event) {
        console.log('fin-cell-click', event.detail);
    });
```
