### ISSUE TITLE
Filtering data, i.e. grid.setTableFilter()

### ISSUE THREAD

**Issue by noahtaylor** [openfin/fin-hypergrid#351]
Are there any examples of filtering anywhere.  I have tried to follow the docs here:
http://openfin.github.io/fin-hypergrid/doc/ParserCQL.html for correct CQL syntax but was unable to get it to work. 
Also I have tried to follow the JSON syntax but again could not get it work.

@joneit

**Comment by Dwaynekj** [comment]
Have you seen this page http://openfin.github.io/fin-hypergrid/doc/tutorial-filter-api.html

**Comment by noahtaylor** [comment]
Thanks for sending me that.  I tried to read through this but I still don't understand how to do a basic query.  I just want to be able to filter all rows that contain certain values.  For example:
Suppose I have column A and B.  I want to only show all rows where A = "123".  How is this possible?
I tried something like this:
grid.setTableFilter('"A" = "123"');
grid.applyAnalytics();
grid.behaviorChanged();

but I just get:
unncaught FilterTreeError: SQL WHERE clause parser: ParserSqlError: Expected valid column name or alias

I have also tried many other variations on the CQL syntax
grid.setTableFilter('A LIKE "123"');
or
grid.setTableFilter("'A' = '123'');
etc. ...

**Comment by Dwaynekj** [comment]
@joneit

**Comment by noahtaylor** [comment]
@joneit I also tried doing:
grid.getGlobalFilter().columnFilters.add({
        children: [{
            column: 'A',
            operator: '=',
            operand: '123'
        }],
        type: 'columnFilter'
    });

but get:

Uncaught TypeError: Cannot read property 'submenu' of undefined(anonymous function) @ index.js:116build @ index.js:100makeElement @ FilterLeaf.js:383createView @ FilterLeaf.js:109setState @ FilterNode.js:220initialize @ FilterNode.js:179recur @ index.js:176recur @ index.js:174recur @ index.js:174initializePrototypeChain @ index.js:169Constructor @ index.js:67add @ FilterTree.js:237loadState @ FilterTree.js:168setState @ FilterNode.js:221initialize @ FilterNode.js:179recur @ index.js:176recur @ index.js:174recur @ index.js:174initializePrototypeChain @ index.js:169Constructor @ index.js:67add @ FilterTree.js:237filterByAlias @ VM10994 autoquoting-hyper-grid.js:211onclick @ VM11785 autoQuoting:86

**Comment by joneit** [comment]
@noahtaylor Thanks for your input. Sorry to hear your having issues. I just tried some tests in our [demo]() by entering the following statements in the Chrome debugger:

```javascript
g.setTableFilter('height = 70')
```

This worked fine.

I then tried:

```javascript
g.setTableFilter('height = 70 and birthState LIKE \'A%\'');
g.setTableFilter('height = 70 and "birthState" LIKE \'New%\'');
```

These also worked fine.

Nevertheless, we will create a trouble ticket to test and review filter API to make sure everything is working per design.

In the mean time, it would be very helpful if you could send me more information, such as the browser you are using (brand, platform, version) and an example .html file that exhibits the issues you are having.

JE

**Comment by noahtaylor** [comment]
@joneit I am running chrome Version 52.0.2743.116 m

I tried using your exact syntax but it doesn't work.  I get:

Unncaught FilterTreeError: SQL WHERE clause parser: ParserSqlError: Expected valid column name or alias.
parseStateString @ FilterNode.js:278
setState @ FilterNode.js:216
setTableFilterState @ DefaultFilter.js:409
setTableFilter @ JSON.js:797
setTableFilter @ Behavior.js:1643
setTableFilter @ Hypergrid.js:3191

The only thing I can think of is that I am defining my table differently, i.e. I define my columns using
grid.behavior.setFields([]);

whereas you use a custom schema definition

I'll see about making a js fiddle or something

**Comment by noahtaylor** [comment]
@joneit I fixed the issue by defining custom schema as you had done in the demo.  I didn't realise I needed to define both field and custom schema names for columns
