### ISSUE TITLE
htmlint task fails

### ISSUE THREAD

**Issue by mikehaas763** [openfin/fin-hypergrid#36]
I have a basic clone of the repo. Ran npm install and bower install then ran grunt serve. However, I'm getting a failure when running the htmllint task. I get a simple "Fatal error: Unexpected token E" and the serve command exits.

For now I just removed the htmllint task from the grunt file. Is anyone else getting this?

**Comment by stevewirts** [comment]
I don't see this, and I don't push to master unless lint completes,
maybe you got a corrupted git pull?

**Comment by mikehaas763** [comment]
I'll try another clone and look into it more to see if I can get more useful information.

**Comment by stevewirts** [comment]
Let me know I definitely want to fix this asap!
Thanks

~steve

**Comment by mikehaas763** [comment]
Just to keep you updated, looks like this relates to jzaefferer/grunt-html#65

**Comment by Dwaynekj** [comment]
Closing ticket. The master branch will be updated soon to reflect the 'big-refactor' branch (v2 release). If you have a continued issue with big-refactor branch please open a new ticket or email support@openfin.co
