### ISSUE TITLE
Official discussion area

### ISSUE THREAD

**Issue by mikehaas763** [openfin/fin-hypergrid#37]
I can continue creating issues to ask questions, but just thought I'd suggest a gitter.im, slack and/or irc channel for anyone who wants to have conversations and get help etc.

**Comment by Dwaynekj** [comment]
Hey @mikehaas763 
Sorry for the EXTREMELY long reply. Rest assured that the project will have better response times to inquires and more community supported documentation moving forward. Also note that we have promoted master tor reflect a non-polymerized version of the Grid.

In terms of your original question, we feel at the moment github issues will suffice based on the time we need to focus on completing the remaining feature set (we're still only a two man team)
