### ISSUE TITLE
Some questions/suggestions

### ISSUE THREAD

**Issue by shaulid** [openfin/fin-hypergrid#371]
Hi,

Thanks for sharing hypergrid.
I've looked more deeply into hypergrid and the examples and would like to know whether you plan to add the following features (or I missed them somehow):
1. Allowing rows with different heights, inside the same grid. This includes multiline cells that will make the whole row width bigger.
2. Allowing subgrids. That is, a row can be expandable so that below it we'll have another hypergrid instance with a completely different table (with different columns).
   Currently I understand that you can stack up rows in a tree but they all belong to the same table and have the same columns.
3. Better mobile support? Perhaps allow navigation using touch gestures: finger pinching for zooming in/out, scrolling such as in the mobile versions of Excel/Google Sheets (this means that e.g. scrolling using the finger will scroll the data but leave the ABCDE... and 123... row numbers where they are).

Please also comment about your thoughts about the difficulty I could have if I try to implement the changes myself (I can try if it's not too hard).

Thank you very much for this product.

**Comment by Dwaynekj** [comment]
@shaulid We can take a look at your inquiry tomorrow

**Comment by Dwaynekj** [comment]
Hey @shaulid 
#1
#2 Not at the moment.
#3 We don't have immediate plans for mobile support, but its a long term consideration.

**Comment by shaulid** [comment]
#1 Here's an example - it's very simple, just rows with different heights.
![different-heights](https://cloud.githubusercontent.com/assets/15046011/19869060/5d6c357a-9fb3-11e6-918d-b459a2a342ea.png)

Anyhow considering your other answers and since I need subgrids I'll look at other solutions for now.

Thanks (can close this issue)

**Comment by Dwaynekj** [comment]
@shaulid I see.

We'll keep your comments in mind for the future
