### ISSUE TITLE
What function does rendering invoke to get the height a row should be rendered as?

### ISSUE THREAD

**Issue by mikehaas763** [openfin/fin-hypergrid#38]
I've never really gotten into game style development (render loop, etc) so I'm having a hard time tracking down and debugging to discover functionality.

When I adjust the height of a row to make it bigger (using the default behavior) what function is invoked that gets the height that the row should be rendered as?

**Comment by stevewirts** [comment]
look at the behavior-base, there is a function getRowHeight(y), the
overrides are stored in the tableState object

**Comment by mikehaas763** [comment]
Thanks. I had seen that and set a break point but it was never hit. Something must have gotten messed up with my debugger because it was being hit after refreshing.
