### ISSUE TITLE
feature: autowrap content to a fixed cell(column) width and expand vertically

### ISSUE THREAD

**Issue by mikehaas763** [openfin/fin-hypergrid#39]
Essentially what I mean is auto row height similar to what kendo and other grids offer. I know the grid currently supports the user adjusting row heights but this is a whole other beast that gets even more complicated when "paging" through chucks of remote data sets from a server.

I'd love to brainstorm and hash out from a high-level how this would actually work.

**Comment by stevewirts** [comment]
auto column widths is in place currently,
I'll be putting this feature in for rows as well shortly..
also, you'll be happy to hear that we are going in the direction of filling
out hypergrid-lite to eventually replace fin-hypergrid.  I'm confident we
can keep the API the same, without polymer. ;)

**Comment by mikehaas763** [comment]
That's great news and I think it's the right move for the grid.

**Comment by Dwaynekj** [comment]
Closing ticket. The master branch will be updated soon to reflect the 'big-refactor' branch (v2 release). If you have a continued issue with big-refactor branch please open a new ticket or email support@openfin.co
