### ISSUE TITLE
Remove checkboxes in number column

### ISSUE THREAD

**Issue by stofte** [openfin/fin-hypergrid#398]
Is there an API to disable the checkboxes that appear on the number column?

**Comment by Dwaynekj** [comment]
@stofte You can try 

```
       YourGrid.addProperties({
            showRowNumbers: false
        });
```

**Comment by stofte** [comment]
I did try that, but that removes the whole column, which is a bit more then I wanted ;)

The png's renders pretty badly on high density pixel screens, so I'd really like to get rid of it.

**Comment by Dwaynekj** [comment]
Ah. Well we are using the png [here](https://github.com/openfin/fin-hypergrid/blob/master/src/lib/Renderer.js#L1011) from [here](https://github.com/openfin/fin-hypergrid/blob/master/src/lib/Renderer.js#L9) and [here](https://github.com/openfin/fin-hypergrid/blob/master/images/index.js#L16)

Possibly we can just make the images configurable? @joneit

**Comment by Dwaynekj** [comment]
@stofte You can do fin.Hypergrid.images.checked = document.querySelector('img');
to set it to an empty image.

**Comment by stofte** [comment]
@Dwaynekj that did the trick, thanks alot :-)
