### ISSUE TITLE
Cross browser/mobile eventing

### ISSUE THREAD

**Issue by rdepena** [openfin/fin-hypergrid#4]
example trackpad, scroll, touch events.

current implementation: https://github.com/stevewirts/fin-canvas

Desired result: 
Device and browser agnostic scrolling, navigation and input events.

**Comment by OscarGodson** [comment]
I can't even scroll in most of the demos. Like these ones I can't scroll at all http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/demo.html

**Comment by stevewirts** [comment]
Were working on this right now

**Comment by snackycracky** [comment]
Can you give a little more insights on this upcoming fix?

**Comment by OscarGodson** [comment]
@dadambickford ^

**Comment by Dwaynekj** [comment]
Hey all, I'm closing this ticket. The master branch will be updated to reflect the 'big-refactor' branch (v2 release). I encourage you to try out the functionality on that branch and if you still have a concern, please open a new ticket or email support@openfin.co

**Comment by OscarGodson** [comment]
Are the demos updated as well yet?

**Comment by Dwaynekj** [comment]
The primary demo at the moment.

http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/examples/v0.2/index.html

We will be making new demos as we centralize the product features and remove extraneous functionality
