### ISSUE TITLE
Scroll bars in demo's are hard to find and use

### ISSUE THREAD

**Issue by dannyc** [openfin/fin-hypergrid#40]
Hi.
First off this is one of the most amazing demo's I've seen in a while! It really pushes the boundaries of what thought possible.
One issue is it seems the custom scroll bars are at the edge of the canvas as opposed to the width of the content as can be seen in your json-standalone demo. Can there be a way that you calculate how much width you've actually used and move the scroll bar to that edge as opposed to the page edge?
Also one other suggestion- the scroll bars are a little too subtle in all the demos. I realize it's a feature that they only show on hover and are semi-transparent and are on top of the content, but to someone used to ordinary browser scroll bars I struggled even to realize that there was a way to scroll at all. And even after finding the scroll bars they were so transparent I had trouble seeing how much progress I had made. Is there any way to make the scroll bars more pronounced in the demos?
Thanks and huge kudos.

**Comment by stevewirts** [comment]
Hi Danny,

Thanks for interest in the project.
We've had alot of suggestions about the scrollbars and definitely intend to
revisit them as soon as practical.
We're in the middle of a major refactor/rewrite of the core functionality
at the moment, the scrollbars are on the list.

~steve

**Comment by Dwaynekj** [comment]
Closing ticket. The master branch will be updated soon to reflect the 'big-refactor' branch (v2 release). If you have a continued issue with big-refactor branch please open a new ticket or email support@openfin.co
