### ISSUE TITLE
Bower Releases

### ISSUE THREAD

**Issue by AaronGhent** [openfin/fin-hypergrid#41]
Hey are you able to tag or release your fin-hypergrid version for better and faster bower support

because currently there's only one version available 0.0.0 but in your bower.json you have 0.2.12 defined it would be nice to see this released via github for better bower integration using semver :)

**Comment by stevewirts** [comment]
Hi Arron

thanks for your interest in hypergrid...

currently we're in the middle of major cleanup/refactoring/enhancement;
post this we will do a proper bower deployment.  this is a few weeks away

~steve

**Comment by AaronGhent** [comment]
nice one thx :+1:
