### ISSUE TITLE
Hypergrid without node.js in a chromium cefsharp environment

### ISSUE THREAD

**Issue by chhadidg** [openfin/fin-hypergrid#426]
Is it possible to make this "awesome" datagrid as a standalone application with no web background or webserver?

I got the basic grid to work, but sorting and filtering seems to require a webserver/node.js installation. Is this true?

I am just curious how much customization would be required.

Thanks for any comments.
Christian

**Comment by Dwaynekj** [comment]
Hey @chhadidg. Thanks for trying out Hypergrid. You don't need to have any background processes running. You can simply use the grid as an in-memory solution, meaning that you can pass a JSON array of homogenous objects to the grid.

i.e.

```
[
{
  head1: "a",
  head2: "a2",
  head 3: "a3"
},
{
  head1: "b",
  head2: "b2",
  head 3: "b3"
},
]
```

**Comment by Dwaynekj** [comment]
As for filtering for sorting:

With version v1.2.9 in the interim (v 1.3.0 is scheduled for this week)..  you could try to load this [demo](https://github.com/openfin/fin-hypergrid/blob/develop/demo/sorting-and-filtering-pipeline.html). We will soon have this demo on our CDN.

IMPORTANT
Our sorting and filtering add-on code are now considered examples that won't be maintained, the core focus of Hypergrid is to enable you to present data that you have sorted or filtered. So feel free to use them as reference along with the upcoming wikis for information on how to create your own sorting and filtering information
