### ISSUE TITLE
request for event

### ISSUE THREAD

**Issue by snackycracky** [openfin/fin-hypergrid#43]
Hello,
I would like to request the event 'fin-header-click'. So that when a column is sorted by the user this event should fire.
At the moment this is a workaround:
```
jsonGrid.addFinEventListener('fin-click', function(event) { 
            if(event.detail.gridCell.y === -1){
                let x = event.detail.gridCell.x
                console.log(`sorting for column requested: ${colums[x+1]).name}`);
            }
        });

```

Maybe in the event details it should provide the information if the column is sorted asc or desc.

Also I want to overwrite the sorting functionality.

-----------update: 

I would need the functionality to totally mute the default sorting behaviour and sort the table by providing new sorted data manually.

**Comment by snackycracky** [comment]
basically: how can I disable a feature: fin-hypergrid-feature-column-sorting ?

**Comment by osbert-messerfs** [comment]
Actually the current implementation of fin-hypergird-feature-column-sorting isn't really about sorting but rather a general handler for header clicking; if you look at fin-hypergrid-behavior-base.js you will find a function fixedRowClicked which you can override on your own behavior object to alter or disable the sort behavior.

**Comment by snackycracky** [comment]
:+1:
