### ISSUE TITLE
setTimeout in Demo

### ISSUE THREAD

**Issue by snackycracky** [openfin/fin-hypergrid#45]
Why are there two times setTimeout defined in bclys index.html ? Just for demonstration or is this some kind of workaround?
https://github.com/openfin/fin-hypergrid/blob/master/examples/bclys/index.html#L302

**Comment by stevewirts** [comment]
this is strictly for demonstration of memento state change capabilities

**Comment by snackycracky** [comment]
This demo leverages some events which are not documented:
- fin-context-menu
- fin-column-selection-changed
- fin-row-selection-changed

are those events going to be in production ?

Also this event uses the methods `getSelectedRows()` and `getSelectedColumns()`:
```
        jsonGrid.addFinEventListener('fin-selection-changed', function(e){
            console.log(jsonGrid.getSelectedRows(), jsonGrid.getSelectedColumns(), jsonGrid.getSelections());
        });

```
will this also in Production ?

**Comment by snackycracky** [comment]
also I saw the function of 'multi-column' sorting :)
