### ISSUE TITLE
How Do I Build Vulcanised Component?

### ISSUE THREAD

**Issue by opticyclic** [openfin/fin-hypergrid#46]
I want to try out the big-refactor branch that is a work in progress as I am very interested in grouping.
What are the build steps to generated the vulcanised component?

**Comment by stevewirts** [comment]
Im not at my machine today
Tomorrow I will post detailed Instructions

**Comment by stevewirts** [comment]
Hi folks,

actually the big refactor branch is all you need to build the vulcanized
component.
1) create a parent directory
2) cd into 'parent'
3) git clone https://github.com/openfin/fin-hypergrid.git
4) git checkout feature/big-refactor
5) npm install
6) bower install
7) grunt serve
8) http://localhost:9000/fin-hypergrid/examples/bclys/index.html

grunt will auto build the dev and min(vulcanized) html web components for
you on any save of a dependent component

let me know if this helps

~steve
