### ISSUE TITLE
Deprecated Usage for Shadow Dom related API / CSS

### ISSUE THREAD

**Issue by osbert-messerfs** [openfin/fin-hypergrid#47]
I visited http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/demo.html today and the latest Chrome (ver. 45) issues the following warnings:
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

I understand these are not hypergrid issue but rather polymer's; there are different versions of the way forward discussed in the issue list that it will support Polymer 1.0 or it will detach from Polymer, both of which I hope could solve the issue, but may I know how big the change will be so I could estimate the difficulty to migrate to the new framework?

**Comment by stevewirts** [comment]
were currently 75% ported off of polymer within the feature/big-refactor branch at a the moment, hopefully we'll be finished with this in the next few weeks :)

**Comment by osbert-messerfs** [comment]
That's great news to hear. Thanks very much Steve!
