### ISSUE TITLE
sorting will result in an infinite loop

### ISSUE THREAD

**Issue by snackycracky** [openfin/fin-hypergrid#48]
Hello,
I am experiencing a high cpu load after some time with the table.
Today I found out that `getFixedRowValue` on the behavior model is somehow trapped in an endless loop.

To reproduce please put in an log message in `getFixedRowValue` in `fin-hypergrid-behavior-json.js` and trigger a column sort:

https://github.com/openfin/fin-hypergrid/blob/master/polymer/js/behaviors/fin-hypergrid-behavior-json.js#L448 is where you can put `console.log('test',x)` and then click on column sort in the json behavior example.

I am having problems continuing writing my own sort solution because of this issue.

**Comment by snackycracky** [comment]
It's not about triggering the sorting. It's about the table-state having a sorting defined.

**Comment by stevewirts** [comment]
thanks,
I'll look into this

**Comment by snackycracky** [comment]
After further investigation the problem seems to occur if `jsonModel.setData(data)` is called multiple times (and maybe the sorting does not really matter).

**Comment by snackycracky** [comment]
The Problem occurs not deterministically but definitely as long as the state has some ordering information.

**Comment by snackycracky** [comment]
Also the CPU-Load rises if you go to http://openfin.github.io/example-fin-hypergrid-behavior-json/ and scroll a little down.
The CPU-Load will stay up as long as you are on the page. If you go to another tab in chrome, the CPU-Load will drop. When one switches back to the fin-hypergrid tab then the CPU-Load increases again.

**Comment by stevewirts** [comment]
this should be fixed now

**Comment by snackycracky** [comment]
Which commits are you referring to ?
