### ISSUE TITLE
Tree view shows triangle on leaf rows in develop branch

### ISSUE THREAD

**Issue by jjrv** [openfin/fin-hypergrid#483]
In the `develop` branch, the tree view seems to show a triangle even on rows that are not expandable, confusing the user.

**Comment by Dwaynekj** [comment]
@jjrv @joneit and I will look into this 

Please note we will be removing Tree View from Hypergrid in favor of providing a generic view on hierarchal data while the user defines and shapes the semantic meaning of that data. Certainly we may reuse logic of tree view to leverage displaying the triangles in a tree column

**Comment by jjrv** [comment]
@Dwaynekj Thanks! The bug is clearly visible in `demo/tree-view.html` after `git checkout develop`, `npm install` and `gulp`. Just click on "Treeview", "Expand All Rows" and there's a triangle on each row.

**Comment by Dwaynekj** [comment]
@jjrv I'll provide an update for you this week

**Comment by Dwaynekj** [comment]
@jjrv This is scheduled for the next sprint

**Comment by Dwaynekj** [comment]
If this is urgent, we can offer guidance. We want Hypergrid to be more community driven

**Comment by Dwaynekj** [comment]
@jjrv  

As stated in https://github.com/openfin/fin-hypergrid/issues/488

Everyone can take a look at an review this example on the alpha branch for how to use [tree-column.html](https://github.com/openfin/fin-hypergrid/blob/develop/demo/tree-column.html) to build your own tree-view. Hypergrid's implementation of tree-view is of course going away

Please also take a look at the notes in https://github.com/openfin/fin-hypergrid/issues/569. Any feedback is appreciated.
