### ISSUE TITLE
Adding

### ISSUE THREAD

**Issue by kiro** [openfin/fin-hypergrid#49]
Hi, how can I append data to the grid, without having to reload the whole data set?

**Comment by stevewirts** [comment]
var myModel = myGrid.getBehavior();
myModel.getData().push(anotherRow1);
myModel.getData().push(anotherRow2);
myModel.getData().push(anotherRow3);
myModel.changed();

**Comment by kiro** [comment]
Thanks!

**Comment by KapoorG** [comment]
Hello,
How do I get exiting record (by column name) and update it ? I can't get the example working.

**Comment by Dwaynekj** [comment]
@KapoorG Please open a new ticket or email support@openfin.co Thanks!

**Comment by noahtaylor** [comment]
@stevewirts This doesn't work for me.  a) getBehavior() doesn't exist anymore but I can call myGrid.behavior instead.  However, even after I push in data values and call myModel.changed() nothing happens

**Comment by Dwaynekj** [comment]
@noahtaylor Would you mind opening a new ticket. The context of this ticket refers to the old polymer version of Hypergrid that we no longer support. The Readme on master branch points to up-to-date information.

Additionally @stevewirts is no longer at openfin so you can direct questions to @joneit or myself

**Comment by noahtaylor** [comment]
@Dwaynekj actually I was able to resolve this by going through the release notes.  A new addRow method has been added.  
var myModel = grid.behavior;
myModel.dataModel.addRow(record);
myModel.applyAnalytics();
grid.behaviorChanged();

Thanks for getting back to me.

**Comment by Dwaynekj** [comment]
Great thanks
