### ISSUE TITLE
Tree should expand only when clicked cell is in a drilldown column.

### ISSUE THREAD

**Issue by jjrv** [openfin/fin-hypergrid#493]
[This function](https://github.com/openfin/fin-hypergrid/blob/9be421c5d086a6f091b21aeab7f2151a4db95584/src/dataModels/JSON.js#L523-L534) according to its description is supposed to return if a drilldown column is clicked, but it doesn't pass the event to `toggleRow` which then calls `this.isDrillDown()` with no arguments, disregarding which column was actually clicked.

The issue is visible in the [online demo](http://openfin.github.io/fin-hypergrid/tree-view.html). Attempting to select a cell in the second column also toggles the tree branch on that row.

**Comment by Dwaynekj** [comment]
I'll tack this on to the investigation into tree-view I have planned for this week

**Comment by Dwaynekj** [comment]
I left a review on your PR
