### ISSUE TITLE
fin-click event details are incorrect

### ISSUE THREAD

**Issue by jjrv** [openfin/fin-hypergrid#496]
The `fin-click` event handler receives an object with properties `detail.row` and `detail.gridCell.y`. Both appear to be incorrect, and refer to the row below the one that was clicked, without considering how the grid was scrolled. That means clicking the top visible row triggers an event for the second row of the entire grid.

This is my workaround:

```TypeScript
grid.addEventListener('fin-click', (event) => {
  let row = grid.getRow(event.detail.gridCell.y + grid.vScrollValue - 1);
  // Handle the event.
});
```

By the way the [renderer tutorial](http://openfin.github.io/fin-hypergrid/doc/tutorial-cell-renderer.html) says:

```JavaScript
jsonGrid.addFinEventListener('fin-cell-click', function(e){
```

Seems both the method and event name have since changed.

**Comment by Dwaynekj** [comment]
@jjrv We will have this in our backlog for a future sprint. Not enough bandwidth to address this bug right now as our queue is full

**Comment by joneit** [comment]
@jjrv @Dwaynekj These are known issues with the version currently on master (**v.1.2.1**).

The new version **v1.3.0,** scheduled to be merged to master _this evening,_ provides `e.detail.dataCell` which contains (in `.y`) the zero-based scrolled row index, which is what you're looking for.

Furthermore, `e.detail.row` now returns the correct data row.

Note that `e.detail.gridCell` was correct as is; it refers to the currently viewable grid rows, _i.e.,_ the _visible_ grid rows (not the _data_ rows).

Caution that v1.3.0 has breaking changes!

**Comment by Dwaynekj** [comment]
@jjrv This https://github.com/openfin/fin-hypergrid/pull/498 should address your concerns.
