### ISSUE TITLE
Adding data doesn't update the scrollbar position

### ISSUE THREAD

**Issue by angelaigreja** [openfin/fin-hypergrid#50]
Using the event fin-scroll-y, I have created a infinite scrolling list.

My problem is that when I scroll to the end, the scrollbar doesn't move after the data is loaded.
Taking a looks at your README, it seems the scrollbar is not tied to the rows.

Is there an easy way to fix this problem?

**Comment by stevewirts** [comment]
call myModel.changed();

**Comment by angelaigreja** [comment]
It doesn't fix the issue since I am doing a setData.

Would it work if instead, I added the new rows to using the getData?

**Comment by stevewirts** [comment]
Hypergid uses the array object you give it
So yes
Push new rows into the result of getData()
And call changed ();

**Comment by angelaigreja** [comment]
Thanks.

**Comment by angelaigreja** [comment]
This has been fixed in the meantime. Thanks for the replies.
