### ISSUE TITLE
Tree column Rendering and Display Configuration

### ISSUE THREAD

**Issue by nclsclsn** [openfin/fin-hypergrid#501]
I have created a new renderer extending the SimpleCell in order to highlight some parts of the text.
It works fine with the normal view but the highlighting does not apply to the Tree column of the aggregation view despite having configured the column property with the proper renderer.

Also, as I wanted to remove the selection checkboxes in the Tree column, I have noticed that grid.behavior.dataModel.getCell doesn't explore the Tree column and starts directly at 1 instead of 0.
Is there any way I can play with the Tree column rendering?

I have at least managed to change the column name by explicitely setting the schema for the aggregator source after turning on the aggregation view:
   ``grid.behavior.dataModel.findDataSourceByType('aggregator').schema = ctrl.aggregationSchema;``
Where my first schema element is:
    ``{name: 'Tree', header: 'Risk bucket', type: 'string'},``

**Comment by Dwaynekj** [comment]
@nclsclsn I will get back to you this week

**Comment by Dwaynekj** [comment]
@nclsclsn With regards tot he tree column. The selection checkboxes should be in its own column. Where are you seeing otherwise?

**Comment by nclsclsn** [comment]
I have the checkboxes from the selection column (as of showRowNumbers = true) and I have the checkboxes in the tree column.

You can check the checkboxes in the selection colum and it does automatically check the checkbox in the tree column. Same with select all.

If you check the checkboxes on the tree column, it has the same effect than the arrow icon i.e. it expands or collapse so it adds some unnecessary redundancy which is why I wanted to remove the checkbox. The select all checkbox in the tree column does nothing. One could expect to offer expand/collapse all if you want to maintain the checkbox.

![tree-selection-box](https://cloud.githubusercontent.com/assets/10231872/23017759/7a33dca6-f433-11e6-8ba8-910061f17bbc.png)

**Comment by Dwaynekj** [comment]
@nclsclsn This should be resolved in the new alpha

**Comment by Dwaynekj** [comment]
Everyone can take a look at an review this example on the alpha branch [tree-column.html](https://github.com/openfin/fin-hypergrid/blob/develop/demo/tree-column.html). 

Please also take a look at the notes in https://github.com/openfin/fin-hypergrid/issues/569. Any feedback is appreciated.

@nclsclsn You can style the new tree Column as a though its a regular column by accessing `grid.renderer.visibleColumns[-1] if is shown.
