### ISSUE TITLE
Pipeline stashing

### ISSUE THREAD

**Issue by nclsclsn** [openfin/fin-hypergrid#503]
I'm not sure if pipeline stashing is working properly.

When looking at setPipeline in dataModels/JSON.js, the function is stashing the new DataSources while it should stash the current ones (i.e. this.DataSources) before replacing them by DataSources.
In practice, my pipeline starts with DataSourceGlobalFilter and DataSourceSorterComposite then it becomes the aggregation pipeline when i turn on the feature and i can still see 3 data sources in my pipeline when I turn it off.

Also, I was wondering why you're stashing the data source constructors and not the data source instances directly?

**Comment by Dwaynekj** [comment]
Short answer...

We will address this as we aim to black box our dataModels in the next sprint. This will allow the pipeline notion as something that should be user defined.

Longer Answer..

The reasoning for using the constructors is that we wanted to be able to recreate the pipeline after reinitializing the grid with serialized state. However, we feel that we have leaked too much internals of the dataSourceOrigin and pipelines. 

We are going to fall back on the original implementor's notion of providing the dataModel as an interface potentially looking like such (getValue, setValue, getRowCount, getSchema, setSchema). Then the application layer can define how those methods should function. In short, we are moving towards black boxing dataModel.

**Comment by Dwaynekj** [comment]
@nclsclsn Confirming that this will be removed from the core dataModel interface and offered as example code.
