### ISSUE TITLE
Unexpected usage pattern for the hyper sorter 

### ISSUE THREAD

**Issue by nclsclsn** [openfin/fin-hypergrid#504]
I'm using the alpha branch 1.2.20 and I wanted not to rely on the datasaur code.

For filtering, I'm using Hypergrid.analytics.DataSourceGlobalFilter in the pipeline with a custom filter that I set or not depending on a flag without relying on a controller.

For sorting, I wanted to use the hypersorter directly.
To achieve that, I'm using Hypergrid.analytics.DataSourceSorterComposite in the pipeline and I'm setting the hyperfilter as a controller but I actually needed to do more including an inelegant wrap.
For sorting to be effective, I had to do:
``
        var sorterDataSource = grid.behavior.dataModel.findDataSourceByType('sorter');
        sorterDataSource.set(ctrl.wrappedHyperSorter);
``
with 
``
        ctrl.wrappedHyperSorter = {
            prop: function (property) {
                if (property === 'sorts') {
                    return grid.plugins.hypersorter.sorts;
                }
            }
        };
``
To mimic the filtering behavior, I would have expected not to use the hypersorter as a controller and directly do:
``
        var sorterDataSource = grid.behavior.dataModel.findDataSourceByType('sorter');
        sorterDataSource.set(grid.plugins.hypersorter);
``

**Comment by Dwaynekj** [comment]
@nclsclsn Thanks for pointing this out. As I externalized this, I will take a look. I should be able to get to this next week.

**Comment by Dwaynekj** [comment]
*For all interested readers. Please note that we are going to be dropping support for our aggregations, filtering, sorting and analytics services. Our reasoning is defined [here](https://github.com/openfin/fin-hypergrid/blob/master/OVERVIEW.md). We will provide an API to allow you to update the grid's view of nested data and or subgrids, but the actual grouping or aggregations etc, must be done on your end. In short, Hypergrid is a view. That being said our existing analytics services are being exported out of Openfin's github domain, but they will still be available for private forking by those interested.*

**Comment by Dwaynekj** [comment]
@nclsclsn Some urgent items came up. We will have to revisit this in another week or so. Sorry for the delay.

**Comment by Dwaynekj** [comment]
@nclsclsn As with my response on similar tickets. I encourage you to take a fork of the add-ons and to treat their existing implementation as example code. You can keep an eye on https://github.com/openfin/fin-hypergrid/issues/572 which abstracts away controllers and pipelines from the DataModel Interface allowing you to configure it yourself
