### ISSUE TITLE
Possible conflict between sorting, totals and aggregation

### ISSUE THREAD

**Issue by nclsclsn** [openfin/fin-hypergrid#505]
Sorting does not go back to a good stage when coming back from the aggregation pipeline.
As I was inspecting the code in my browser, I observed that the sorting data source was passed on with the Totals subgrid instead of the data one which explains why I couldn't see any effect.
Could there be any conflict between sorting, totals and aggregation?

**Comment by Dwaynekj** [comment]
It is likely that the pipelines are not fully compatible and that their state may leak a bit. As we are ripping them out, we won't be doing further maintenance of them

Sorry again to have to post this notice. Its for everyone else's sake. I aware that you understand our current roadmap

*For all interested readers. Please note that we are going to be dropping support for our aggregations, filtering, sorting and analytics services. Our reasoning is defined [here](https://github.com/openfin/fin-hypergrid/blob/master/OVERVIEW.md). We will provide an API to allow you to update the grid's view of nested data and or subgrids, but the actual grouping or aggregations etc, must be done on your end. In short, Hypergrid is a view. That being said our existing analytics services are being exported out of Openfin's github domain, but they will still be available for private forking by those interested.*

**Comment by Dwaynekj** [comment]
*For all interested readers. Please note that we are going to be dropping support for our aggregations, filtering, sorting and analytics services. Our reasoning is defined [here](https://github.com/openfin/fin-hypergrid/blob/master/OVERVIEW.md). We will provide an API to allow you to update the grid's view of nested data and or subgrids, but the actual grouping or aggregations etc, must be done on your end. In short, Hypergrid is a view. That being said our existing analytics services are being exported out of Openfin's github domain, but they will still be available for private forking by those interested.*

**Comment by Dwaynekj** [comment]
@nclsclsn Some urgent items came up. We will have to revisit this in another week or so. Sorry for the delay.

**Comment by Dwaynekj** [comment]
@nclsclsn Confirming that this will be removed from the core dataModel interface and offered as example code.
