### ISSUE TITLE
Dynamic noDataMessage

### ISSUE THREAD

**Issue by nclsclsn** [openfin/fin-hypergrid#506]
The noDataMessage works well when the grid is set with no data but it does not render dynamically i.e. when the grid has nothing to display either because of filtering or following the removal of all rows.
This is not a big deal as I'm using grid.setInfo explicitely on those cases but it would be worth considering adding it to the library?

**Comment by Dwaynekj** [comment]
We thought of this use case but we at the moment do not want to enforce this UX pattern and as you did left it up to the prerogative of the user
