### ISSUE TITLE
Visualization of recalculated aggregates

### ISSUE THREAD

**Issue by nclsclsn** [openfin/fin-hypergrid#507]
The expandAllRows feature is very helpful and I've added an auto expand functionality in my app to make sure rows are expanded each time a condition changes i.e. new grouping, filtering, sorting, recalculated aggregates.
Expanding all rows creates a visual blink as the grid is repainted.
I guess it's fine when setting new groups or applying a new filter/sort but it's annoying when recalculating the aggregates.

My aggregates are calculated via a parametrized function and these parameters can change regularly.
Right now, i call setAggregatesGroup with the same parameters each time one of the parameters change. Is there a better way to recalculate aggregates?

This visual blink can also be my own doing when inappropriately calling either grid.behavior.reindex(), grid.behavior.changed() or grid.repaint()
Can you please remind me in which situation I should call which?

**Comment by Dwaynekj** [comment]
Re: Visual Blink

Reindex should be called when the state of your pipeline objects changes or on a setData call

Behavior Changed should be called when the state of a row, column or columns is changed. Such as when you resize a column, change their order, toggle a row or set a dynamic property. Many of this is already down internally on your behalf if you use the appropriate API method.

Repaint is called whenever you have updated the state of the grid. The repaint is not immediate however, but a flag that is set and checked on an interval. You may also make use of the `continuousRepaint` flag which leverages requestAnimationFrame

**Comment by Dwaynekj** [comment]
Re: Parametized Aggregations function

*For all interested readers. Please note that we are going to be dropping support for our aggregations, filtering, sorting and analytics services. Our reasoning is defined [here](https://github.com/openfin/fin-hypergrid/blob/master/OVERVIEW.md). We will provide an API to allow you to update the grid's view of nested data and or subgrids, but the actual grouping or aggregations etc, must be done on your end. In short, Hypergrid is a view. That being said our existing analytics services are being exported out of Openfin's github domain, but they will still be available for private forking by those interested.*


The Hyper-analytics Aggregations module's internal state tracks an array of functions as `aggregates` and builds a schema to describe the columns (see [here](https://github.com/openfin/hyper-analytics/blob/master/js/DataSourceAggregator.js#L157)). If you wish to avoid resending duplicative functions for the sake of one function, you could certainly fork the module and provide easier helper utilities.

**Comment by Dwaynekj** [comment]
*For all interested readers. Please note that we are going to be dropping support for our aggregations, filtering, sorting and analytics services. Our reasoning is defined [here](https://github.com/openfin/fin-hypergrid/blob/master/OVERVIEW.md). We will provide an API to allow you to update the grid's view of nested data and or subgrids, but the actual grouping or aggregations etc, must be done on your end. In short, Hypergrid is a view. That being said our existing analytics services are being exported out of Openfin's github domain, but they will still be available for private forking by those interested.*

**Comment by Dwaynekj** [comment]
@nclsclsn We are replacing support for aggregations with support for a tree column api. Please review the example [here](https://github.com/openfin/fin-hypergrid/blob/alpha/demo/tree-column.html)

**Comment by satheeq** [comment]
@Dwaynekj the provided tree-column api demo URL is **broken/not working**. Can we get a working demo?
