### ISSUE TITLE
Schema issue with group-view plugin

### ISSUE THREAD

**Issue by nclsclsn** [openfin/fin-hypergrid#509]
I don't need the group-view plugin in my app but I have briefly tried it either in your demo or locally.
There seems to be a schema issue when inserting the Tree column.
I'm aware you're not focusing on data transformers anymore but I'm wondering if it's not coming from the schema management of the core library.

**Comment by Dwaynekj** [comment]
We are pushing to master today. This has been resolved and can be seen on the tip of the alpha branch

**Comment by Dwaynekj** [comment]
*For all interested readers. Please note that we are going to be dropping support for our aggregations, filtering, sorting and analytics services. Our reasoning is defined [here](https://github.com/openfin/fin-hypergrid/blob/master/OVERVIEW.md). We will provide an API to allow you to update the grid's view of nested data and or subgrids, but the actual grouping or aggregations etc, must be done on your end. In short, Hypergrid is a view. That being said our existing analytics services are being exported out of Openfin's github domain, but they will still be available for private forking by those interested.*

**Comment by Dwaynekj** [comment]
@nclsclsn I will close this ticket if there is still an issue, let us know if there is still an issue
