### ISSUE TITLE
How to define new cell editor in React?

### ISSUE THREAD

**Issue by ooblahman** [openfin/fin-hypergrid#51]
I'm using Hypergrid inside a React component, and setting its initial properties as in this ```componentDidMount``` function:
```
componentDidMount() {
    document.addEventListener('polymer-ready', () => {
    myHypergrid.getBehavior().initializeCellEditor('my-number-cell-editor');
    myHypergrid.getBehavior().getCellEditorAt = function(x, y) {
        var cellEditor = this.grid.cellEditors['numberfield'];
        return cellEditor;
    };
}
```
following the "add new cell editor" instructions on the main page. However, I cannot import the cell editor HTML file in ```Index.html```, as that requires importing Polymer, and doing so produces "Polymer is not a defined function" errors on render. What is the correct way to import cell editor HTML into React?

**Comment by stevewirts** [comment]
HI,

this was a demo we knocked together awhile back, I think it should help
you....

https://github.com/openfin/Hyperblotter/blob/release/from-demo/src/javascript/components/hypergrid.js

~steve
