### ISSUE TITLE
Does The Big Refactor Include These Features?

### ISSUE THREAD

**Issue by opticyclic** [openfin/fin-hypergrid#52]
I need the following features for my application and I would like to know if the big-refactor branch contains them currently or if it is planned for future.

* Filtering
* Sorting
* Column grouping
* Column auto-sizing /re-sizing
* Fixed/Frozen columns
* Tree/Aggregated view
* Coloured headers
* Coloured cells / text formatters
* Export to csv

I can see some of them in http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/demo.html?theme=candy

I can't see 
* Filtering
* Column auto-sizing /re-sizing  (README mentions this though)
* Fixed/Frozen columns (README mentions this though)
* Tree/Aggregated view
* Export to csv (needs to work without a plugin installed in Excel)

Thanks for all your work on this excellent component!

**Comment by stevewirts** [comment]
all of these features are in the big-refactor branch

**Comment by snackycracky** [comment]
hey,
could you say a word about the progress for this branch? Some kind of timeplan ...
thx :)

**Comment by joneit** [comment]
Nils,

This branch is still in active development. We have not yet reached v1.0, but have made a lot of progress. This version is no longer a Polymer component.

We also want to refine the API reference which is currently inadequate.

The latest changes and additions were merged in this morning. The `index.html` demo file as well as the `index.js` and `index.min.js` libarary files are on our Github Pages CDN [here](http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/examples/v0.2).

The demo has a lot of features turned on including all the ones you mentioned you couldn't see (except export).

Jonathan

**Comment by opticyclic** [comment]
Thanks for the update! This is looking great!

You might want to work on the CSS for that demo though.... ;)

**Comment by mercmobily** [comment]
> This version is no longer a Polymer component.

May I ask you why not? I am going through the code in the big-refactor branch, and polymer is still a dependency...
I found you while looking for a data grid web component. Are you going to stop being a web component as such? Why so?

Thank you!

**Comment by Dwaynekj** [comment]
@mercmobily All polymer components dependencies have now been removed.

**Comment by Dwaynekj** [comment]
I will update the readme to reflect the final list of big-refactor changes and send an update in this channel
