### ISSUE TITLE
How to refresh data

### ISSUE THREAD

**Issue by mrudangit** [openfin/fin-hypergrid#531]
grid.setData() is the only way to update new data?

**Comment by mrudangit** [comment]
what if we want to only few cells of particular row

**Comment by jjrv** [comment]
You can do:

```JavaScript
grid.getRow(i).columnName = 'new content';
```

After all updates are done and you want to show them:

```JavaScript
grid.repaint();
```

**Comment by mrudangit** [comment]
I see that's helpful 

however any way to access row by some key

e.g. rows are list of stock items and price update came for say AAPL want to update just AAPL row with new market data 

is it possible ?

**Comment by Dwaynekj** [comment]
@mrudangit Thanks for using Hypergrid!

 We don't have primary keys associated with the bounded data. We would encourage you to build a mapping of the rows sent to the grid back to your original indexes and then you can simply getRow by index as @jjrv suggests.. I hesitantly point you to this [add-on](https://github.com/openfin/fin-hypergrid/blob/master/add-ons/row-by-id.js) which probably has the methods you need, but you must understand we offer it as example. We will be removing this code from the repo shortly

**Comment by Dwaynekj** [comment]
@mrudangit I also wanted to point that our new default render only updates the cells that has been changed, that is unless there is change in the overall shape of the grid dimensions or a scroll action

**Comment by mrudangit** [comment]
thanks for the info. 

Also , does grid hols the data by reference ?

e.g. we have 

var row = {symbol: 'APPL', name: 'Apple Inc.', prevclose: 93.13};

var data = [ row];


grid.setData(data);

now if I update row.prevClose=99.99;

and do grid.repaint()

will new values be displayed ?

**Comment by mrudangit** [comment]
`<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>

<body>

    <script src="https://openfin.github.io/fin-hypergrid/build/fin-hypergrid.js"></script>

    <script>
        var aapl = {
            symbol: 'APPL',
            name: 'Apple Inc.',
            prevclose: 93.13
        };

        var data = [
            aapl, {
                symbol: 'MSFT',
                name: 'Microsoft Corporation',
                prevclose: 51.91
            }, {
                symbol: 'TSLA',
                name: 'Tesla Motors Inc.',
                prevclose: 196.40
            }, {
                symbol: 'IBM',
                name: 'International Business Machines Corp',
                prevclose: 155.35
            }
        ];
        var grid = new fin.Hypergrid();
        grid.setData(data);

        setInterval(function() {
            aapl.prevclose = Math.random() * 100;
            grid.repaint();
        }, 2000);
    </script>
</body>

</html>`

**Comment by mrudangit** [comment]
above seems to be working i see AAPL prevClose is refreshing

**Comment by Dwaynekj** [comment]
You enable continuousRepaint without needing setInterval

```
        grid.addProperties({
            enableContinuousRepaint: true
        });
```

**Comment by mrudangit** [comment]
Nice!!

I guess need to go thru docs thoroughly. 

However, does it have performance implications?

**Comment by Dwaynekj** [comment]
@mrudangit We could also use some help on documentation!
Continuous repaint calls repaint which simply sets a flag. Hypergrid paints on requestAnimationFrame if that flag is set
