### ISSUE TITLE
How to render selection border?

### ISSUE THREAD

**Issue by ooblahman** [openfin/fin-hypergrid#54]
I'm currently rendering borders around a selection by overriding the cellRenderer, and calling gc.lineTo() on manually computed cell border edges. This results in <http://puu.sh/kXyQr/43e03b8d57.png>. However, it's quite expensive to compute the rendered edges on every cell render, and it seems like something far easier like directly painting the selection rectangle on the canvas is doable. Moreover, gridlines get painted over the selection rectangle in the screenshot above.

Does there exist an exposed API to do this, or else is there some way to paint a border around all active selections on the canvas?

**Comment by stevewirts** [comment]
all of that info is available already on the config object....
you don't need to compute it yourself...

I'll get you rendering hook out, early tomorrow
