### ISSUE TITLE
getting started instructions doesnt result in a working grid

### ISSUE THREAD

**Issue by raj-sidhu** [openfin/fin-hypergrid#55]
Hi,

Followed the instruction in getting started, ran a grunt serve, browser appeared, contents in top splitter pane works, but nothing in the bottom. No errors in npm or bower installs. 

Chrome reports two errors:

Uncaught TypeError: inMemoryGrid.getBehavior is not a function(anonymous function) @ demo.html:366(anonymous function) @ polymer.js:11702queue.flushReadyCallbacks @ polymer.js:11508
demo.html:520 Uncaught TypeError: jsonGrid.getBehavior is not a function(anonymous function) @ demo.html:520(anonymous function) @ polymer.js:11702queue.flushReadyCallbacks @ polymer.js:11508

The failing lines are coming from index.html, any ideas?

thanks.

**Comment by raj-sidhu** [comment]
any ideas or pointers would be appreciated. I will try a reinstall and setup again today.

tia.

**Comment by stevewirts** [comment]
Hi Raj,

I've gone through the setup steps and things work nicely for me.
Can you be more specific about what it is that is not working for you?

thanks
~steve

**Comment by raj-sidhu** [comment]
HI Steve,

I just tried again and got the same error. I'm running windows 10.

I cloned the git repo, did a npm install and then a bower install. I then ran grunt serve.

A browser popped up, but disapeared before I could see what was in it, then another appeared. This browser contains the top part of the demo, but the actual grid is missing.

The error is the same as before, getBehavior is not defined, could you let me know where this function comes from so I can try and find it?

**Comment by stevewirts** [comment]
can you open the demo in chrome from the github pages?
you may need to force a build as well,  try resaving fin-hypergrid.js.

**Comment by raj-sidhu** [comment]
Hi Steve,

Yes the online demo works fine.

I resaved fin-hypergrid.js and then ran grunt serve again. It seemed to pick up the change, but the end result was the same, top menu with a splitter and nothing below it.

D:\dev\f\fin-hypergrid
Running "serve" task

Running "express:all" (express) task

Running "express-server:all" (express-server) task
Web server started on port:9000, hostname: 0.0.0.0 [pid: 760]

Running "polymer-component-sync:default" (polymer-component-sync) task
creating main file fin-hypergrid.js
adding polymer/html\fin-hypergrid.html
adding polymer/css\fin-hypergrid.css
adding test\fin-hypergrid.js
creating index.html
creating test/index.html
...

![image](https://cloud.githubusercontent.com/assets/14542466/10878589/a2110462-8146-11e5-85db-38b6da30acc5.png)

Anything else I can try?

thanks for your help.

**Comment by raj-sidhu** [comment]
HI Steve,

I think i'm getting closer to the issue. If I debug the online version getBehaviour goes into fin-hypergrid.js. The difference being my local copy just has a few lines in it while the online version is much much bigger.

My version:
'use strict';

(function() {

    Polymer('fin-hypergrid', { /* jshint ignore:line  */ });

})();

Looking more closely out at the grunt serve output I noticed one thing I never saw previously:

Running "shell:jsdocs" (shell) task
Warning: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "./jsdoc.sh"
'.' is not recognized as an internal or external command,
operable program or batch file.
 Use --force to continue.

Aborted due to warnings.

I bet this might be the issue, if you see this before I fix it what command is it trying to run? 

cheers.

**Comment by stevewirts** [comment]
grunt serve --force

**Comment by raj-sidhu** [comment]
no joy i'm afraid, same error and fin-hypergrid.js is still tiny.

**Comment by raj-sidhu** [comment]
Steve quick update, I couldnt get it to work, but I did get the hypergrid json example to work using the cdn(github) version of fin-hypergrid.dev.html.

This is good enough for now. I will need to get it working eventually though.

thanks for your help.

**Comment by Dwaynekj** [comment]
Closing ticket. The master branch will be updated soon to reflect the 'big-refactor' branch (v2 release). If you have a continued issue with big-refactor branch please open a new ticket or email support@openfin.co
