### ISSUE TITLE
Rectangles larger than viewing window are rendered incorrectly

### ISSUE THREAD

**Issue by ooblahman** [openfin/fin-hypergrid#56]
I'm using addExtraRenderer to paint a rectangle on the grid. When drawing a rectangles larger than the viewing window (visible columns x visible rows), it gets drawn in the wrong place:

http://puu.sh/l6VcH/932ee6ee6a.png

**Comment by stevewirts** [comment]
It needs to be clipped by the viewport I think

**Comment by Dwaynekj** [comment]
Closing ticket. The master branch will be updated soon to reflect the 'big-refactor' branch (v2 release). If you have a continued issue with big-refactor branch please open a new ticket or email support@openfin.co
