### ISSUE TITLE
How can we append the <fin-hypergrid> imperatively

### ISSUE THREAD

**Issue by alvaro-itrs** [openfin/fin-hypergrid#57]
I am trying to append the <fin-hypergrid> element imperatively, from javascript code.
(We made hypergrid work with the <fin-hypergrid> in the html document without problems) 

While in Polymer 1.0 there are clear instructions about how to proceed:
http://docs.polymerchina.org/1.0/docs/devguide/local-dom.html

it is not the same case for Polymer 0.5
We are experiencing something like in:
https://github.com/Polymer/polymer/issues/835

Do you have instructions about how to do this?

Thank you in advance!

**Comment by stevewirts** [comment]
Hi Alvaro,

Unfortunately we do  not at this time.

We are currently porting hypergrid out of polymer 0.5 with plans to "wrap"
it with Polymer 1.0 when its ready

we are targeting eoy for this

~steve

On Tue, Nov 3, 2015 at 11:08 AM, Alvaro Santamaria <notifications@github.com

**Comment by alvaro-itrs** [comment]
Thank you, Steve.
We are looking forward to being able to use hypergrid. 

Cheers,
Álvaro

**Comment by GanapathyRajalingam** [comment]
Hi Steve,

Any update as when we will be able to use finHyperGrid with Polymer 1.0?
Awaiting to use finHypergrid in our apps.

~Ganapathy.

**Comment by stevewirts** [comment]
Look at the big-refactor branch theres a polymer wrapper example
