### ISSUE TITLE
When a webpage consists of multiple hypergrids, editors will stay within the first hypergrid where it is created

### ISSUE THREAD

**Issue by osbert-messerfs** [openfin/fin-hypergrid#58]
I presume it might not be an issue in the big refactor version but I haven't look at that yet;

In editAt function in fin-hypergrid.js, code below

```
if (!cellEditor.isAdded) {    
    cellEditor.isAdded = true;
    this.shadowRoot.appendChild(cellEditor);
}
```
does not handle the scenario where the cellEditor is attached to another hypergrid. I would suggest to make a change similar to:
```
if (cellEditor.isAdded) {
    if (cellEditor.grid !== this) {
        this.shadowRoot.appendChild(cellEditor);
    }
} else {
    cellEditor.isAdded = true;
    this.shadowRoot.appendChild(cellEditor);
}
```

Just my 2 cents for the awesome project.

**Comment by Dwaynekj** [comment]
@osbert-messerfs Hello. Sorry for the delay in getting back to you. We can take look at updating the api for big-refactor

**Comment by osbert-messerfs** [comment]
@Dwaynekj No worries. I am currently using the big-refactor branch so let me know if I should create a pull request from my fork instead.

**Comment by Dwaynekj** [comment]
Yes if you don't mind
