### ISSUE TITLE
DataModel Abstraction: Example sorting and filtering

### ISSUE THREAD

**Issue by juliostanley** [openfin/fin-hypergrid#582]
Hi, the performance of hypergrid is great! However, I am a little lost with the documentation.

What are the steps to enable sorting and filtering, for the version 1.3.0 of hypergrid (using hyper-analytics tree view data source)?

---------------

From master (1.3.0), I am trying to use the tree-view add-on demo  (I see that in develop, this is removed). On chrome the sorter does not sort the treeview columns (expected sorting at each depth), and the Filter does not seem to work. For IE11 there is a failure on rendering the headers.

I am using the sample add-ons:
- grouped headers
- tree view (with the old drilldown and rowById which I seems will be deprecated/merged into hypergrid)

I see hyper-analytics 0.12.0 allows adding a DataSource filter and sorter to the pipeline, but I am not familiar enough with the HyperGrid stack to know which steps I am missing, or what would replace the filter/sorter controller, and or plugins, in order to make the filter and sorter work with the Tree View

**Comment by Dwaynekj** [comment]
@juliostanley We can address your concerns later this week

**Comment by juliostanley** [comment]
@dwaynekj sounds good, thanks.

**Comment by Dwaynekj** [comment]
@juliostanley Could you send me an email to dwayne@openfin.co. I tried emailing you but I must've wrote it down wrong

**Comment by Dwaynekj** [comment]
@juliostanley So we have a prelimary example of how sorting interface would look *at the moment* [here](https://github.com/openfin/fin-hypergrid/blob/master/demo/sorting-example.html) particularly we are overriding dataModel.[getRow](https://github.com/openfin/fin-hypergrid/blob/master/demo/sorting-example.html#L790) and [getValue](https://github.com/openfin/fin-hypergrid/blob/master/demo/sorting-example.html#L83)

We are planning in this [ticket](https://github.com/openfin/fin-hypergrid/issues/517) in the current sprint to simplify the dataModel interface to just 4 or so verbs to be implemented by user. Then with  filtering, sorting, virtual data, etc, the grid simply renders the value returned from getValue, getRow. It won't care where the data is coming from or how it is managed. The hypergrid simplify renderers cells as fast it can once it has its value, and for special cell like header, tree column cells you can define the renderer to implement a UX that indicate what state this data is in (i.e. add an up triangle in the header cell of the relevant column).

**Comment by Dwaynekj** [comment]
Closing in favor of https://github.com/openfin/fin-hypergrid/issues/547 and https://github.com/openfin/fin-hypergrid/issues/546
