### ISSUE TITLE
Export the data in pdf row by row

### ISSUE THREAD

**Issue by tuv123** [openfin/fin-hypergrid#585]
Hi,
I want to extract the table data in pdf file.
So, if the code is like following, how can I get this data into the object and export it?
Please provide some APIs.
There are some functions used in-
"fin-hypergrid-master/demo/simple-column-sorting-pipeline.html" but I can not use them to extract. 

<!doctype html>
 <html>
 <head>
     <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
 </head>
 <body>
     <div id="fin-grid"></div>
 
     <script src="https://openfin.github.io/fin-hypergrid/build/fin-hypergrid.js"></script>
     <script>
         var grid = new fin.Hypergrid('#fin-grid', {
             data: [
                 { 'symbol':'APPL', 'name':'Apple Inc.', 'prevclose':'93.13' },
                 { 'symbol':'MSFT', 'name':'Microsoft Corporation', 'prevclose':'51.91' },
                 { 'symbol':'TSLA', 'name':'Tesla Motors Inc.', 'prevclose':'196.40' },
                 { 'symbol':'IBM', 'name':'International Business Machines Corp', 'prevclose':'155.35' }
             ]
         });
         
     </script>
 </body>
 </html>
grid.

**Comment by Dwaynekj** [comment]
@tuv123 Hello! The data that is passed into the grid, is the same data we would return back to you when exporting it. It is the array of objects used during instantiation or `setData`
