### ISSUE TITLE
How to apply custom themes / styles in the grid

### ISSUE THREAD

**Issue by prabhur1983** [openfin/fin-hypergrid#586]
HI Team,

I am looking for apply custom themes on the grid. Need some tutorials on this topic.

the grid has properties of theme in it. Can you please post some help on this?

**Comment by joneit** [comment]
Thanks for your input! We will post a wiki on "themes" in the next 24-48 hrs and will let you know when available.

**Comment by Dwaynekj** [comment]
@prabhur1983 The themes wiki is up https://github.com/openfin/fin-hypergrid/wiki/Themes
