### ISSUE TITLE
License problems with dependencies using GPL v3.0

### ISSUE THREAD

**Issue by hugoeanogueira** [openfin/fin-hypergrid#589]
Hi! It looks like [inject-stylesheet-template](https://github.com/joneit/inject-stylesheet-template) is under the GPL v3.0 license.
Correct me if I'm wrong (please do!), but I think that this means that hypergrid and the projects using it must be under the same license.

@joneit can you please confirm this?
Thanks!

**Comment by mistic** [comment]
Hey @hugoeanogueira I think you're right and this is also a HUGE problem for me! @joneit @Dwaynekj  Do u think it will be possible to change the inject-stylesheet-template license to the MIT one for example?

**Comment by Dwaynekj** [comment]
@hugoeanogueira @mistic Thanks for pointing this out, we will change this asap!

**Comment by Dwaynekj** [comment]
This has been resolved in the new master. v2.0.0 is out!

**Comment by hugoeanogueira** [comment]
Thanks!
