### ISSUE TITLE
Alpha version in npm

### ISSUE THREAD

**Issue by glb-eibermanm** [openfin/fin-hypergrid#595]
Would you provide the alpha version to npm? this way I can automate the fix for multiples grids.

Thanks for advance.

**Comment by Dwaynekj** [comment]
@glb-eibermanm Thanks for using the grid. You can use https://docs.npmjs.com/files/package.json#git-urls-as-dependencies to specify a particular branch in your package.json

**Comment by glb-eibermanm** [comment]
Maybe Im doing something wrong but this is not working for me:
npm install git://github.com/openfin/fin-hypergrid.git#alpha
What its missing?

**Comment by Dwaynekj** [comment]
Try `npm install openfin/fin-hypergrid#alpha`
