### ISSUE TITLE
Online demo not working

### ISSUE THREAD

**Issue by joshmyzie2** [openfin/fin-hypergrid#73]
I've tried the online demo in the latest version of Firefox and Chrome on Windows 7 with 32-bit kdb+ running the sorttable.q script, but after refreshing the page, I'm not seeing anything load.

There are a couple errors in the console about missing JS files:

![untitled](https://cloud.githubusercontent.com/assets/12620937/11468290/4b4a82c8-9746-11e5-8041-931d31c53c9a.jpg)

**Comment by snackycracky** [comment]
+1 wanted to pitch your table on Thursday and had the same issue. The pitch was fine anyways ;)

**Comment by joshmyzie2** [comment]
Here are the errors in Chrome:

![untitled2](https://cloud.githubusercontent.com/assets/12620937/11468391/04bc8b20-9747-11e5-9165-6f400f2c037e.jpg)

I don't know anything about javascript or web development, so don't know how to fix this, but looks like just some broken links.

**Comment by snackycracky** [comment]
currently they are working on the feature/big-refactor branch and removing polymer.

**Comment by joshmyzie2** [comment]
@snackycracky  Ah ok, thanks.  I'll give it another try in a few days then.

**Comment by stevewirts** [comment]
we will fix the main branch today, this should be working

**Comment by stevewirts** [comment]
this is fixed

**Comment by joshmyzie2** [comment]
@stevewirts Thanks, the main demos are now working.

I just had to change `.j.c` to `.j.k` in the q script.  I'm guessing you had defined a custom JSON function?

**Comment by stevewirts** [comment]
The name changed between versions of Q I think
