### ISSUE TITLE
Documentation on Changes

### ISSUE THREAD

**Issue by emanchan** [openfin/fin-hypergrid#84]
Hey guys,

I've been following this project and I was wondering if more clarification/details could be added in regards to the changes introduced with v0.2 (which is the big-refactor milestone if I'm not mistaken). 

It seems like hypergrid is now contained within an 'index.js' file for the examples now? In reference towards: https://github.com/openfin/fin-hypergrid/tree/master/examples/v0.2 

I've noticed that there's a lot of changed or removed apis with:

https://github.com/openfin/fin-hypergrid/blob/master/fin-hypergrid.dev.html

that currently break my application using this older version of fin-hypergrid.dev.html: 

https://github.com/openfin/fin-hypergrid/commit/f705bd43ec7df77e138471157ebabd84c4b75a3d

Features in particular that seem to have been changed are column global styling and rollups/tree formatting. 

Thanks,

Ethan

**Comment by Dwaynekj** [comment]
I will be updating the Readme on the big-reactor milestone. I'll keep you posted
