### ISSUE TITLE
Highlight row selection 

### ISSUE THREAD

**Issue by kiro** [openfin/fin-hypergrid#88]
Is there a way to highlight the whole row, when clicking on a cell?

**Comment by snackycracky** [comment]
we did that in cellProvider.getCell = (config) => {…}

and there we checked if the row should be coloured or not:

if (_.includes(this.selectedThings.map(o => o.thing), config.row.thing)) {
  config.fgColor = '#ffffff';
  config.bgColor = '#777777’;    //highlight the whole row.
}

we update the selection in the array “this.selectedThings” by hooking to the event “fin-selection-changed” 

be aware that there can be multiple selections in the table with the “CTRL” Key.

**Comment by kiro** [comment]
Thanks!
