### ISSUE TITLE
i can't run demo.html

### ISSUE THREAD

**Issue by sinanguler** [openfin/fin-hypergrid#91]
I'm using local files. i was download all required files and project.
Examples folder html files working well. but demo.html page receiving errors begin with
"polymer-micro.html:74 Uncaught TypeError: prototype.registerCallback is not a function"

**Comment by Dwaynekj** [comment]
Hey all, I'm closing this ticket. The master branch will be updated to reflect the 'big-refactor' branch (v2 release). I encourage you to try out the functionality on that branch and if you still have a concern, please open a new ticket or email support@openfin.co
