### ISSUE TITLE
Vertical scrollbar does not work well on IE11

### ISSUE THREAD

**Issue by Shengairong** [openfin/fin-hypergrid#93]
The vertical scrollbar cannot be dragged by mouse on IE11.
Below demo has the issue.
http://openfin.github.io/fin-hypergrid/components/fin-hypergrid/demo.html

**Comment by Dwaynekj** [comment]
Hey all, I'm closing this ticket. The master branch will be updated to reflect the 'big-refactor' branch (v2 release). I encourage you to try out the functionality on that branch and if you still have a concern, please open a new ticket or email support@openfin.co
