### ISSUE TITLE
this.canvas undefined if rendering hypergrid with any delay

### ISSUE THREAD

**Issue by ooblahman** [openfin/fin-hypergrid#94]
I'm using hypergrid in React, and previously I was rendering the parent component immediately, attaching a `polymer-ready` event listener in `componentDidMount` to customize hypergrid properties when ready. Now, I have some login flow that introduces a delay in the rendering of hypergrid, and therefore the `polymer-ready` event fires before  the listener is attached. 

Theoretically, this should mean I can go ahead and perform my customizations eagerly, but in reality I get a `Uncaught TypeError: Cannot read property 'addEventListener' of undefined` error in `this.canvas` of `addFinEventListener`. 

The difference is between these two blocks:
```
// with polymer-ready listener, no delay
render(<App />, document.getElementById('main'));

// without polymer-ready  listener, but with delay
setTimeout(() =>
  render(<App />, document.getElementById('main')),
  5000);
```
I have no idea if this is a Polymer problem or a hypergrid problem. Any pointers as to why this happens? It seems any situation where I don't render hypergrid immediately on app load fails.

**Comment by stevewirts** [comment]
Did you try using the latest build from the big-refactor branch?

**Comment by ooblahman** [comment]
We're maintaining a fork of master with some cosmetic changes (column/row dragging) so using the big-refactor branch is not really an option for us right now, given the API changes. Is there anything in the master branch that would cause this problem? For example, does the canvas element get attached to hypergrid asynchronously or something?

**Comment by ooblahman** [comment]
That seems to be true. Is there a 'canvas-ready' event that is fired when the canvas is attached? If not, could you point me to the file or line where the canvas is instantiated, and I might fire such an event myself?

**Comment by joneit** [comment]
Look in `../fin-canvas/fin-canvas.js` polymer component, in the `ready` method. (This is a separate component, with its own Gruntfile.js, etc.)

**Comment by Dwaynekj** [comment]
Hey all, I'm closing this ticket. The master branch will be updated to reflect the 'big-refactor' branch (v2 release). I encourage you to try out the functionality on that branch and if you still have a concern, please open a new ticket or email support@openfin.co
